#!/usr/bin/env bash

mt_packages=(nvidia \
                 nvidia-utils \
                 nvidia-settings \
                 lib32-nvidia-utils)

if [ "${1}" = "uninstall" ]; then
    sudo pacman -R "${mt_packages[@]}" --noconfirm
else
    sudo pacman -S "${mt_packages[@]}" --noconfirm
fi
