#!/usr/bin/env bash

# Uninstall nouveau
sudo pacman -R xf86-video-nouveau --noconfirm

# Install latest Nvidia drivers
. ~/.scripts/linux/mt-arch-nvidia-latest-setup

# Install prime
sudo pacman -S nvidia-prime --noconfirm

# Install optimus-manager
yay -S optimus-manager optimus-manager-qt --noconfirm
