#!/usr/bin/env bash

mt_response=$(echo -e "Brightness 100%\nBrightness 90%\nBrightness 80%\nBrightness 70%\nBrightness 60%\nBrightness 50%\nBrightness 40%\nBrightness 30%\nBrightness 20%\nBrightness 10%" | rofi -dmenu)

case "${mt_response}" in
    "Brightness 100%")
        xrandr --output "DP-2" --brightness 1.0
        ;;

    "Brightness 90%")
        xrandr --output "DP-2" --brightness 0.9
        ;;

    "Brightness 80%")
        xrandr --output "DP-2" --brightness 0.8
        ;;

    "Brightness 70%")
        xrandr --output "DP-2" --brightness 0.7
        ;;

    "Brightness 60%")
        xrandr --output "DP-2" --brightness 0.6
        ;;

    "Brightness 50%")
        xrandr --output "DP-2" --brightness 0.5
        ;;

    "Brightness 40%")
        xrandr --output "DP-2" --brightness 0.4
        ;;

    "Brightness 30%")
        xrandr --output "DP-2" --brightness 0.3
        ;;

    "Brightness 20%")
        xrandr --output "DP-2" --brightness 0.2
        ;;

    "Brightness 10%")
        xrandr --output "DP-2" --brightness 0.1
        ;;

    *)
        # Ignore
        ;;
esac
