#!/usr/bin/env bash

mt_response=$(echo -e "Brightness 100%\nBrightness 90%\nBrightness 80%\nBrightness 70%\nBrightness 60%\nBrightness 50%\nBrightness 40%\nBrightness 30%\nBrightness 20%\nBrightness 10%" | rofi -dmenu)

case "${mt_response}" in
    "Brightness 100%")
        mt_temp=1.0
        ;;

    "Brightness 90%")
        mt_temp=0.9
        ;;

    "Brightness 80%")
        mt_temp=0.8
        ;;

    "Brightness 70%")
        mt_temp=0.7
        ;;

    "Brightness 60%")
        mt_temp=0.6
        ;;

    "Brightness 50%")
        mt_temp=0.5
        ;;

    "Brightness 40%")
        mt_temp=0.4
        ;;

    "Brightness 30%")
        mt_temp=0.3
        ;;

    "Brightness 20%")
        mt_temp=0.2
        ;;

    "Brightness 10%")
        mt_temp=0.1
        ;;

    *)
        # Ignore
        ;;
esac

xrandr --output "eDP-1" --brightness ${mt_temp}
