#!/usr/bin/env bash

# This script is an add-on to `~/.setup/start` containing device-specific setup
# for 2020 Lenovo ThinkPad X1 Extreme (Excelsior)

# Set .XResources for HiDPI
echo "Xft.dpi: 180" > ~/.Xresources

# Enable bluetooth service
# (This might just be a temporary Arch issue)
systemctl enable bluetooth
systemctl start bluetooth

# Setup Nvidia optimus for GPU
. ~/.scripts/linux/mt-nvidia-optimus-setup

# Fix 'Dummy Output' for audio
echo "options snd_hda_intel dmic_detect=0" | sudo tee /etc/modprobe.d/disable_dmic.conf

# Enable Dolby Atmos Effect through pulseeffects
sudo pacman -S pulseeffects --no-confirm
pulseeffects
bash -c "$(curl -fsSL https://raw.githubusercontent.com/JackHack96/PulseEffects-Presets/master/install.sh)"

# Enable microphone noise reduction
echo "
### Enable Echo/Noise-Cancellation
load-module module-echo-cancel use_master_format=1 aec_method=webrtc aec_args=\"beamforming=1 mic_geometry=-0.0257,0,0,0.0257,0,0\" source_name=echoCancel_source sink_name=echoCancel_sink
set-default-source echoCancel_source
set-default-sink echoCancel_sink" | sudo tee -a /etc/pulse/default.pa

# Improve touchpad experience
echo "options psmouse synaptics_intertouch=1" | sudo tee /etc/modprobe.d/psmouse.conf

# Set up auto-cpufreq for power optimization
paru -S auto-cpufreq --no-confirm
systemctl enable auto-cpufreq
systemctl start auto-cpufreq

# TODO: Implement the rest
