#!/usr/bin/env bash

case "${1}" in
    "shutdown" | "poweroff" )
        systemctl poweroff
        ;;

    "restart" | "reboot" )
        systemctl reboot
        ;;

    "sleep" | "suspend" )
        systemctl suspend
        ;;

    "hibernate" | "poweroff" )
        systemctl hibernate
        ;;

    "awake" )
        systemctl mask sleep.target suspend.target
        ;;

    "sleepy" )
        systemctl unmask sleep.target suspend.target
        ;;

    *)
        echo "Not implemented!"
        ;;
esac
