#!/usr/bin/env bash

# TODO: (entering-the-void) Implement alternate scripts in-place of systemd
case "${1}" in
    "lock")
        i3lock -c 000000
        ;;

    "quit")
        i3-msg exit
        ;;

    "sleep" | "suspend" )
        systemctl suspend
        ;;

    "hibernate" | "poweroff" )
        systemctl hibernate
        ;;

    "shutdown" | "poweroff" )
        systemctl poweroff
        ;;

    "restart" | "reboot" )
        systemctl reboot
        ;;

    "awake" )
        systemctl mask sleep.target suspend.target
        ;;

    "sleepy" )
        systemctl unmask sleep.target suspend.target
        ;;

    *)
        echo "Not implemented!"
        ;;
esac
