#!/usr/bin/env bash

command=$1

# Function to switch power using systemd
switch-power-mode-with-systemd () {
    case "${command}" in
        "lock")
            i3lock -c 000000
            ;;

        "quit")
            i3-msg exit
            ;;

        "sleep" | "suspend" )
            systemctl suspend
            ;;

        "hibernate" | "poweroff" )
            systemctl hibernate
            ;;

        "shutdown" | "poweroff" )
            systemctl poweroff
            ;;

        "restart" | "reboot" )
            systemctl reboot
            ;;

        "awake" )
            systemctl mask sleep.target suspend.target
            ;;

        "sleepy" )
            systemctl unmask sleep.target suspend.target
            ;;

        *)
            echo "Not implemented!"
            ;;
    esac
}

# Function to switch power using runit
switch-power-mode-with-runit () {
    case "${command}" in
        "lock")
            i3lock -c 000000
            ;;

        "quit")
            i3-msg exit
            ;;

        "sleep" | "suspend" )
            loginctl suspend
            ;;

        "hibernate" | "poweroff" )
            loginctl hibernate
            ;;

        "shutdown" | "poweroff" )
            loginctl poweroff
            ;;

        "restart" | "reboot" )
            loginctl reboot
            ;;

        "awake" )
            echo "Not implemented!"
            ;;

        "sleepy" )
            echo "Not implemented!"
            ;;

        *)
            echo "Not implemented!"
            ;;
    esac
}

if [ $(command -v systemctl) ]; then
    switch-power-mode-with-systemd
elif [ $(command -v sv) ]; then
    switch-power-mode-with-runit
else
    echo "Not implemented!"
fi
