#!/usr/bin/env bash

# Run update through the primary package manager
if [ $(command -v apt) ]; then
    sudo apt update -y && sudo apt upgrade -y
elif [ $(command -v dnf) ]; then
    sudo dnf update -y
elif [ $(command -v pacman) ]; then
    sudo pacman -Syu
fi

# Update snaps, if available
if [ $(command -v snap) ]; then
    sudo snap refresh
fi

# Update flatpaks, if available
if [ $(command -v flatpak) ]; then
    sudo flatpak update
fi
