#!/usr/bin/env bash

command=$1

case "${command}" in
    minimal | console )
        sudo systemctl disable display-manager.service
        echo "Switched startup mode to console!"
        ;;

    *)
        sudo systemctl enable sddm
        echo "Switched startup mode to graphical!"
        ;;
esac
