#!/usr/bin/env bash

# Run update through the primary package manager
. ~/.assets/libs/bash/detect-platform
case "${tw_platform}" in
    Arch)
        sudo pacman -Syu
        ;;

    Debian)
        sudo apt update -y && sudo apt upgrade -y
        ;;

    Void)
        sudo xbps-install -Syu
        ;;
esac

# Update snaps, if available
if [ $(command -v snap) ]; then
    sudo snap refresh
fi

# Update flatpaks, if available
if [ $(command -v flatpak) ]; then
    sudo flatpak update
fi
