#!/usr/bin/env bash

# Set wallpaper
feh --bg-scale ~/.assets/images/teN7.png

# Enable pulseeffects
pulseeffects --gapplication-service &

# Start udiskie for auto-mounting of removable media
udiskie &

# Set default screen brightness
brightnessctl s 15%

# Play startup sound
mpg123 ~/.assets/sounds/car-startup-sound.mp3 &

# Perform device-specific startup tweaks, if set
if [ -f ~/.device-startup-tweaks ]; then
    . ~/.device-startup-tweaks
fi
