#!/usr/bin/env bash

# Execute device-specific startup scripts
case "${HOSTNAME}" in
    excelsior)
        # Set default screen brightness
        xrandr --output "eDP-1" --brightness 0.3
        ;;

    precision)
        # Nothing here yet
        ;;
esac

# Pick a random wallpaper from the collection
if [ $(command -v fdfind) ]; then
    fdfind . ~/.assets/images -t f -e '.png' -0 | shuf -n1 -z | xargs -0 feh --bg-fill
else
    fd . ~/.assets/images -t f -e '.png' -0 | shuf -n1 -z | xargs -0 feh --bg-fill
fi

# Unmute sound, set volume to 70%
pactl set-sink-mute @DEFAULT_SINK@ false
pactl set-sink-volume @DEFAULT_SINK@ 70%

# Start applications
udiskie &
pCloud &
syncthing 1>/dev/null &

# Perform device-specific startup tweaks, if set
if [ -f ~/.device-startup-tweaks ]; then
    . ~/.device-startup-tweaks
fi

# Turn ON the Numlock
if [ $(command -v numlockx) ]; then
    numlockx
fi

# Play startup sound
mpg123 ~/.assets/sounds/car-revving-sound.mp3 &
