#!/usr/bin/env bash

# Pick a random wallpaper from the collection
if [ $(command -v fdfind) ]; then
    fdfind . ~/.assets/images -t f -e '.png' -0 | shuf -n1 -z | xargs -0 feh --bg-fill
else
    fd . ~/.assets/images -t f -e '.png' -0 | shuf -n1 -z | xargs -0 feh --bg-fill
fi

# Start udiskie for auto-mounting of removable media
udiskie &

# Set default screen brightness
xrandr --output "DP-2" --brightness 0.3

# Play startup sound
mpg123 ~/.assets/sounds/car-startup-sound.mp3 &

# Perform device-specific startup tweaks, if set
if [ -f ~/.device-startup-tweaks ]; then
    . ~/.device-startup-tweaks
fi
