#!/usr/bin/env bash

mt_log "Installing global npm packages..."

sudo npm install -g \
     lite-server \
     nano-server \
     myterminal \
     stay-with-me \
     git-getter \
     re-write

mt_log "All global npm packages installed"
