#!/usr/bin/env bash

mt_temp=$(dirname "$0")
. "$mt_temp/lib" $mt_temp

mt_log "Detecting platform..."
if [ $(uname) = 'Linux' ]; then
    . "$mt_setup_dir/linux/run"
elif [ $(uname) = 'Darwin' ]; then
    . "$mt_setup_dir/mac/run"
else
    mt_abort_setup "Unknown platform found."
fi

mt_confirm_and_source "Generate SSH keys?" \
                      "$mt_setup_dir/generate-ssh-keys" \
                      "Skipped generation of SSH keys"

mt_confirm_and_source "Install NPM packages?" \
                      "$mt_setup_dir/install-npm-packages" \
                      "Skipped installation of NPM packages"

mt_confirm_and_source "Create cloud symlinks?" \
                      "$mt_setup_dir/create-cloud-symlinks" \
                      "Skipped creation of cloud symlinks"

mt_confirm_and_source "Clone GitHub source projects?" \
                      "$mt_setup_dir/clone-github-source-projects" \
                      "Skipped cloning of GitHub source projects"

mt_prompt "Setup is complete, hit any key to reboot..."
sudo reboot 0
