#!/usr/bin/env bash

# Function to set up Docker
mt_task_linux_setup_docker () {
    tw_log "Setting up Docker..."
    tw_execute sudo groupadd docker
    tw_execute sudo gpasswd -a ${USER} docker
    tw_execute sudo systemctl enable docker
}

# Function to change user shell
mt_task_linux_change_user_shell () {
    tw_log "Changing shell to fish..."
    if ! [ "$(cat /etc/shells | grep "/usr/bin/fish")" ]; then
        tw_execute_eval "echo \"/usr/bin/fish\" | sudo tee -a /etc/shells"
    fi
    tw_task_change_user_shell
}

# Function to install toolchain for Rust
mt_task_linux_install_rust_toolchain() {
    tw_log "Installing stable toolchain for Rust..."
    tw_execute rustup toolchain install stable
}

# Function to set up GUI
mt_task_linux_setup_gui () {
    tw_log "Setting up GUI..."
    tw_task_setup_gui false
}

# Function to apply graphical theming
mt_task_linux_apply_graphical_theming () {
    rm -rf ~/_temp

    tw_log "Installing GTK theme..."
    mkdir -p ~/.local/share/themes
    git clone https://github.com/WernerFP/Shades-of-gray-theme.git ~/_temp
    mv ~/_temp/Shades-of* ~/.local/share/themes/
    rm -rf ~/_temp

    tw_log "Installing icon theme..."
    mkdir -p ~/.local/share/icons
    git clone https://github.com/madmaxms/iconpack-obsidian ~/_temp
    mv ~/_temp/Obsidian* ~/.local/share/icons/
    rm -rf ~/_temp

    tw_log "Installing cursor theme..."
    mkdir -p ~/.local/share/icons
    mkdir ~/_temp
    cd ~/_temp
    wget https://github.com/ful1e5/Bibata_Cursor/releases/download/v1.1.1/Bibata.tar.gz
    tar -xvf Bibata.tar.gz
    mv ~/_temp/Bibata-*  ~/.local/share/icons
    cd ~/
    rm -rf ~/_temp
}

# Function to install fonts
mt_task_linux_install_fonts () {
    rm -rf ~/_temp

    tw_log "Installing FontAwesome..."
    mkdir -p ~/.local/share/fonts
    git clone https://github.com/FortAwesome/Font-Awesome ~/_temp
    mv ~/_temp/otfs ~/.local/share/fonts/FontAwesome
    rm -rf ~/_temp

    tw_log "Installing OpenSans..."
    mkdir -p ~/.local/share/fonts
    git clone https://github.com/googlefonts/opensans ~/_temp
    mv ~/_temp/fonts/ttf ~/.local/share/fonts/OpenSans
    rm -rf ~/_temp

    tw_log "Installing Inconsolata..."
    mkdir -p ~/.local/share/fonts
    git clone https://github.com/googlefonts/inconsolata ~/_temp
    mv ~/_temp/fonts/ttf ~/.local/share/fonts/Inconsolata
    rm -rf ~/_temp

    tw_log "Installing Roboto Mono..."
    mkdir -p ~/.local/share/fonts
    git clone https://github.com/googlefonts/RobotoMono ~/_temp
    mv ~/_temp/fonts/ttf ~/.local/share/fonts/RobotoMono
    rm -rf ~/_temp

    tw_log "Installing Droid..."
    mkdir -p ~/.local/share/fonts
    git clone https://github.com/grays/droid-fonts ~/_temp
    mv ~/_temp/droid ~/.local/share/fonts/Droid
    rm -rf ~/_temp

    tw_log "Installing FiraCode..."
    mkdir -p ~/.local/share/fonts
    git clone https://github.com/tonsky/FiraCode ~/_temp
    mv ~/_temp/distr/ttf ~/.local/share/fonts/FiraCode
    rm -rf ~/_temp

    tw_log "Installing FiraCode..."
    mkdir -p ~/.local/share/fonts
    mkdir ~/_temp
    cd ~/_temp
    wget https://github.com/liberationfonts/liberation-fonts/files/6418984/liberation-fonts-ttf-2.1.4.tar.gz
    tar -xvf liberation-fonts-ttf-2.1.4.tar.gz
    mkdir ~/.local/share/fonts/Liberation
    mv ~/_temp/liberation-fonts-ttf-2.1.4/Liberation*  ~/.local/share/fonts/Liberation/
    cd ~/
    rm -rf ~/_temp
}
