#!/usr/bin/env bash

# Run setup for the current OS
if [ $(uname) = 'Linux' ]; then
    . ~/.system/setup/fedora
elif [ $(uname) = 'Darwin' ]; then
    . ~/.system/setup/mac
fi

# Create Dropbox symlinks
. ~/.system/setup/create-dropbox-symlinks
