#!/usr/bin/env bash

# Run setup for the current OS
if [ $(uname) = 'Linux' ]; then
    . ~/.system/setup/fedora/start
elif [ $(uname) = 'Darwin' ]; then
    . ~/.system/setup/mac/start
fi

# Prompt to create cloud symlinks
# Ask to configure cloud services first and confirm that the directories are present
# Once confirmed, proceed with creation of cloud symlinks
read -n1 -r -p "Would you like to create cloud symlinks? (y/n) " k
if [ "$k" == "y" ] || [ "$k" == "Y" ]; then
    echo ""
    read -n1 -r -p "Please make sure the associated cloud services are configured before proceeding. Press any key one done..."
    . ~/.system/setup/create-cloud-symlinks
    echo "Symlinks have now been created"
else
    echo -e "\nSkipped creation of cloud symlinks"
fi

# Prompt to clone GitHub source projects
read -n1 -r -p "Would you like to clone GitHub source projects? (y/n) " k
if [ "$k" == "y" ] || [ "$k" == "Y" ]; then
    echo ""
    . ~/.system/setup/clone-github-source-projects
else
    echo -e "\nSkipped cloning of GitHub source projects"
fi
