#!/usr/bin/env bash

# Init and fetch the git project
cd ~
git init
git remote add origin https://github.com/myTerminal/dotfiles.git
git fetch --all
rm .bash*
git checkout master

# Fetch/update twiner
if [ -d ~/.twiner ]; then
    git -C ~/.twiner pull
else
    git clone https://github.com/myTerminal/twiner.git ~/.twiner
fi

# Start twiner in debug mode
~/.twiner/start debug

# Fetch/update forge
if [ -d ~/.forge ]; then
    git -C ~/.forge pull
else
    git clone https://github.com/myTerminal/forge.git ~/.forge
fi

# Start setup
~/.setup/start
