#!/usr/bin/env bash

case "${1}" in
    "shutdown" | "poweroff" )
        sudo shutdown
        ;;

    "restart" | "reboot" )
        sudo reboot
        ;;

    *)
        echo "Not implemented!"
        ;;
esac
