#!/usr/bin/env bash

# Add RPM Fusion repos
sudo dnf install -y \
     https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
     https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

# Update installed packages
sudo dnf update -y

# Install google-chrome web-browser
sudo dnf install -y \
     https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm

# Install i3 and depdendencies
sudo dnf install -y \
     i3 \
     i3status \
     i3lock \
     feh

# Install essential packages
sudo dnf install -y \
     terminology \
     fish \
     emacs \
     pcmanfm \
     git \
     npm \
     udisks \
     gparted

# Install network packages
sudo dnf install -y \
     dropbox \
     syncthing \
     filezilla \
     transmission \
     thunderbird \
     youtube-dl

# Install multimedia packages
sudo dnf install -y \
     gstreamer \
     vlc \
     clementine \
     audacity \
     gimp \
     shotwell \
     kodi \
     openshot \
     easytag

# Install gaming packages
sudo dnf install -y \
     steam

# Install screencast packages
sudo dnf install -y \
     vokoscreen \
     key-mon

# Install misc packages
sudo dnf install -y \
     libreoffice \
     VirtualBox \
     docker \
     android-file-transfer \
     goldendict \
     calibre

# Install crossover from URL
sudo dnf install -y \
     http://crossover.codeweavers.com/redirect/crossover.rpm

# Install fonts
sudo dnf install -y \
     levien-inconsolata-fonts \
     liberation-mono-fonts \
     google-roboto-mono-fonts \
     google-droid-sans-mono-fonts
sudo dnf copr enable evana/fira-code-fonts -y
sudo dnf install -y fira-code-fonts

# Manual packages
# - Install pCloud Drive from https://www.pcloud.com
# - Install MegaSync from https://mega.nz/sync
# - Install hyper from https://releases.hyper.is/download/rpm
# - Install postman from https://www.getpostman.com/downloads
# - Install Telegram
# - Install Discord

# Missing packages / Find alternative
# - Google Drive
# - licecap
# - Riot
# - Slack
# - Origin
# - Sony Remote play
# - TunnerBear
# - Spotify
# - Inconsolata

# Inbuilt packages
# (None yet)
