#!/usr/bin/env bash

# Install software packages
. ~/.system/setup/fedora/install-packages

# Change shell to fish-shell
chsh -s /bin/fish

# Set up group for docker
sudo groupadd docker
sudo gpasswd -a $USER docker
sudo service docker restart

# Prompt to install Broadcom wl drivers
read -n1 -r -p "Would you like to install Broadcom wireless drivers? (y/n) " k
if [ "$k" == "y" ] || [ "$k" == "Y" ]; then
    echo ""
    . ~/.scripts/mt-fedora23_broadcom_wl_install
else
    echo -e "\nSkipped installation of Broadcom wireless drivers"
fi
