#!/usr/bin/env bash

mt_platform="Unknown"

if [[ -f /bedrock/etc/bedrock-release ]]; then
    mt_platform="Bedrock"
elif [ $(command -v xbps-query) ]; then
    mt_platform="Void"
elif [ $(command -v pacman) ]; then
    mt_platform="Arch"
elif [ $(command -v dnf) ]; then
    mt_platform="Fedora"
elif [[ $(cat /etc/os-release | grep '^ID=' | cut -d '=' -f 2 | cut -d '"' -f 2) == "pop" ]]; then
    mt_platform="Pop"
elif [ $(command -v apt) ]; then
    mt_platform="Debian"
fi
