#!/usr/bin/env bash

# Open vault
sudo mkdir -p /mnt/vault
if [ ! -b /dev/mapper/mirage ]; then
    sudo cryptsetup open /dev/nvme0n1p4 mirage
fi

# Mount vault
if ! mountpoint -q /mnt/vault; then
    sudo mount /dev/mapper/mirage /mnt/vault
fi

# Mount directories
safe_bind() {
    if ! mountpoint -q "$2"; then
        sudo mount -o bind "$1" "$2"
    fi
}
safe_bind /mnt/vault/@store/ismail ~/_store
safe_bind /mnt/vault/@home/ismail/_workspace ~/_workspace
safe_bind /mnt/vault/@home/ismail/.config/emacs ~/.config/emacs
safe_bind /mnt/vault/@home/ismail/.librewolf ~/.librewolf
safe_bind /mnt/vault/@home/ismail/.cache/librewolf ~/.cache/librewolf

# Start bridge apps
emacs &
EMACS_PID=$!
librewolf &
LW_PID=$!

# Pause
echo "------------------------------------------------"
echo "Vault is open and apps are running."
echo "Press [ENTER] to close apps and lock the vault..."
echo "------------------------------------------------"
read -r  # Waits for any keypress

# Start cleanup
echo "Cleaning up..."
kill $EMACS_PID $LW_PID 2>/dev/null
sleep 2

# Unmount binds first (Reverse order is safest)
sudo umount ~/_store
sudo umount ~/_workspace
sudo umount ~/.config/emacs
sudo umount ~/.librewolf
sudo umount ~/.cache/librewolf

# Unmount the main vault
sudo umount /mnt/vault

# Close the LUKS container
sudo cryptsetup close mirage

echo "Vault closed and secured!"
