#!/usr/bin/env bash

# TODO: Add Telegram, Logseq, Waterfox, BetterBird, and KeepassXC

# Install apps
sudo dnf install -y emacs

# Create directories
mkdir -p ~/_store
mkdir -p ~/_workspace
mkdir -p ~/.config/emacs
