#!/usr/bin/env bash

mt_log "Installing other packages for Arch Linux..."

mt_log "Updating all packages..."
sudo pacman -Syu --noconfirm

mt_log "Installing git..."
sudo pacman -S git --noconfirm

mt_log "Installing yay for AUR packages..."
mkdir temp
git clone https://aur.archlinux.org/yay.git ./temp/yay
cd ./temp/yay
makepkg -si
cd ../../
rm -rf ./temp

mt_log "Installing packages from official repos..."
sudo pacman -S \
     i3-wm \
     i3status \
     i3lock \
     feh \
     terminology \
     hyper \
     fish \
     emacs \
     pcmanfm \
     tig \
     aspell \
     aspell-en \
     npm \
     rustup \
     udisks2 \
     gparted \
     syncthing-gtk \
     transmission-gtk \
     youtube-dl \
     thunderbird \
     audacity \
     easytag \
     gimp \
     shotwell \
     openshot \
     clementine \
     vlc \
     gstreamer \
     kodi \
     steam \
     libreoffice-fresh \
     virtualbox \
     docker \
     android-file-transfer \
     ttf-inconsolata \
     ttf-liberation \
     ttf-roboto \
     ttf-roboto-mono \
     ttf-droid \
     ttf-fira-code \
     --noconfirm

mt_log "Installing packages from AUR..."
yay -S \
    google-chrome \
    postman \
    tunnelbear \
    rememberthemilk \
    dynalist-desktop \
    telegram-desktop \
    discord \
    slack-desktop \
    pcloud-drive \
    gamehub \
    vokoscreen \
    key-mon \
    crossover \
    razergenie \
    --noconfirm

# Manual packages
# (None yet)

# Missing packages / Find alternative
# - Google Drive
# - Origin
# - Sony Remote play
# - licecap

# Inbuilt packages
# (None yet)

### More ###

# Install stable toolchain for rust
mt_log "Taking care of a few final things..."
rustup toolchain install stable
