#!/usr/bin/env bash

mt_log "Setting up Arch Linux..."

. "$mt_setup_dir/linux/arch/setup-sources"
. "$mt_setup_dir/linux/arch/install-packages"

mt_confirm_and_source "Setup GUI?" \
                      "$mt_setup_dir/linux/arch/setup-gui" \
                      "Skipped setting up of GUI"

mt_confirm_and_source "Setup Nvidia graphics drivers?" \
                      "$mt_setup_dir/linux/arch/setup-nvidia-graphics-driver" \
                      "Skipped setting up of Nvidia graphics driver"

mt_confirm_and_source "Setup Peripherals?" \
                      "$mt_setup_dir/linux/arch/setup-peripherals" \
                      "Skipped setting up of peripherals"
