#!/usr/bin/env bash

mt_log "Setting up Arch Linux..."

. ~/.setup/linux/arch/setup-repos
. ~/.setup/linux/arch/install-packages

mt_confirm_and_source "Create users?" \
                      ~/.setup/linux/create-users \
                      "Skipped creation of users"

mt_confirm_and_source "Setup GUI?" \
                      ~/.setup/linux/arch/setup-gui \
                      "Skipped setting up of GUI"
