#!/usr/bin/env bash

mt_log "Setting up repos..."

mt_log "Updating all packages..."
sudo pacman -Syu --noconfirm

mt_log "Installing git..."
sudo pacman -S git --noconfirm

mt_log "Installing yay for AUR packages..."
mkdir temp
git clone https://aur.archlinux.org/yay.git ./temp/yay
cd ./temp/yay
makepkg -si
cd ../../
rm -rf ./temp