#!/usr/bin/env bash

mt_log "Setting up peripherals..."

mt_log "Installing packages for Razer devices..."
# Install Razer drivers and polychromatic backend
yay -S \
    python-notify2 \
    openrazer-meta \
    polychromatic \
    --noconfirm
# Install linux headers for dkms
sudo pacman -Syu \
     linux-header \
     --noconfirm
# Add current user to group 'plugdev'
sudo gpasswd -a $USER plugdev

