#!/usr/bin/env bash

# Function to install peripheral drivers
mt_task_linux_install_peripherals_drivers () {
    tw_log "Installing packages for Razer devices..."

    # Install Razer drivers and polychromatic frontend
    tw_execute paru -S \
               python-notify2 \
               openrazer-meta \
               polychromatic \
               --noconfirm

    # Install linux headers for dkms
    tw_execute sudo pacman -Syu \
               linux-headers \
               --noconfirm

    # Add current user to group 'plugdev'
    tw_execute sudo gpasswd -a $USER plugdev
}

# Function to setup startup services
mt_task_linux_setup_startup_services () {
    tw_log "Setting up startup services..."

    # Turn ON Numlock on startup
    tw_execute systemctl enable numLockOnTty.service
    tw_execute systemctl start numLockOnTty.service

    # Setup syncthing service
    tw_execute systemctl --user enable syncthing.service
    tw_execute systemctl --user start syncthing.service

    # Start bluetooth service
    tw_execute systemctl enable bluetooth
    tw_execute systemctl start bluetooth

    # Start ssh service
    tw_execute systemctl enable ssh
    tw_execute systemctl start ssh
}

# Function to perform visual tweaks at GRUB and DM level
mt_task_linux_perform_visual_tweaks () {
    tw_log "Performing visual tweaks..."

    # Install GRUB Fallout theme
    tw_execute sudo pacman -S\
               unzip \
               --noconfirm
    tw_execute_eval "wget -O - https://github.com/shvchk/fallout-grub-theme/raw/master/install.sh | bash"

    # Install sddm-slice theme
    tw_execute sudo pacman -S \
               qt5-graphicaleffects \
               ttf-roboto-mono \
               --noconfirm
    tw_execute sudo git clone \
               https://github.com/RadRussianRus/sddm-slice.git \
               /usr/share/sddm/themes/sddm-slice
    tw_execute_eval "echo \"[Theme]
Current=sddm-slice\" | sudo tee /etc/sddm.conf"
}
