#!/usr/bin/env bash

# Start bluetooth applet for Wayland
if [ "$XDG_SESSION_TYPE" == "wayland" ]; then
    ~/.bin/linux/mt-run-if-not-running blueman-applet
fi

# Play startup sound
STARTUP_SOUNDS_DIR=~/_store/Vault-Mobile/media/startup-sounds
fd . $STARTUP_SOUNDS_DIR -t f -0 | shuf -n1 -z | xargs -0 mpv &
