#!/usr/bin/env bash

# Start pipewire if not already running
if [[ ! $(pgrep pipewire) ]]; then
    dbus-run-session pipewire &
    sleep 1
fi

# Start bluetooth applet for Wayland
if [ "$XDG_SESSION_TYPE" == "wayland" ]; then
    ~/.bin/linux/mt-run-if-not-running blueman-applet &
fi

# Set volume to 70%
pactl set-sink-volume @DEFAULT_SINK@ 70%

# Play startup sound
mpv ~/.assets/sounds/car-revving-sound.mp3 &
