#!/usr/bin/env bash

# Start bluetooth applet for Wayland
if [ "$XDG_SESSION_TYPE" == "wayland" ]; then
    ~/.bin/linux/mt-run-if-not-running blueman-applet
fi

# Play startup sound
mpv ~/.assets/sounds/car-revving-sound.mp3 &
