#!/usr/bin/env bash

# Execute device-specific scripts
case "${HOSTNAME}" in
    polaris)
        brightnessctl s 30%
        ;;

    *)
        # Nothing here yet
        ;;
esac

~/.bin/linux/mt-set-random-wallpaper
