#!/usr/bin/env bash

~/.bin/linux/mt-set-random-wallpaper

if [ "$XDG_SESSION_TYPE" == "wayland" ]; then
    gsettings set org.gnome.desktop.interface gtk-theme 'Bazik_Dark_Red'
    gsettings set org.gnome.desktop.interface icon-theme 'Obsidian-Teal'
    gsettings set org.gnome.desktop.interface cursor-theme 'Bibata-Original-Classic'
    gsettings set org.gnome.desktop.interface font-name 'Open Sans 10'
fi
