#!/usr/bin/env bash

BASE_PATH=~/.scripts/linux/startup/desktop

if [ -f ~/.configure-input-devices ]; then
    . ~/.configure-input-devices
fi

if [ -f ~/.configure-output-devices ]; then
    . ~/.configure-output-devices
fi

${BASE_PATH}/display &
${BASE_PATH}/input &
${BASE_PATH}/audio &
${BASE_PATH}/apps &
