#!/usr/bin/env bash

# Install brew
echo "Installing home-brew"
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# Install cask
echo "Installing cask"
brew tap caskroom/cask

# Install packages only available on brew
echo "Installing packages from brew"
brew install \
     fish \
     node \
     tig \
     aspell \
     syncthing \
     rustup-init \
     youtube-dl

# Install rest of the packages from casks
echo "Installing rest of the packages"
brew cask install \
     hyper \
     emacs \
     google-chrome \
     shiftit \
     postman \
     mounty \
     dropbox \
     google-backup-and-sync \
     megasync \
     filezilla \
     transmission \
     tunnelbear \
     remember-the-milk \
     dynalist \
     riot \
     telegram \
     discord \
     slack \
     thunderbird \
     spotify \
     vlc \
     clementine \
     kodi \
     xnviewmp \
     gimp \
     handbrake \
     kid3 \
     steam \
     origin \
     sony-remoteplay \
     licecap \
     keycastr \
     libreoffice \
     virtualbox \
     crossover \
     docker \
     diffmerge \
     android-file-transfer \
     razer-synapse \
     font-inconsolata \
     font-liberation-sans \
     font-roboto-mono \
     caskroom/fonts/font-fira-code

# Manual packages
# - Install pCloud Drive from https://www.pcloud.com
# - Install Audacity from https://www.fosshub.com/Audacity.html/audacity-macos-2.2.0.dmg
# - Install LAME and FFMPEG from https://lame.buanzo.org/#lameosx64bitdl
# - Install Razer Synapse drivers from http://rzr.to/synapse-mac-download

# Missing packages
# - Droid Sans

# Inbuilt packages
# - Git
