#!/usr/bin/env bash

tw_log "Installing packages from brew..."
tw_execute brew install \
           neofetch \
           wget \
           curl \
           fish \
           tmux \
           ncdu \
           htop \
           fd \
           exa \
           bat \
           ripgrep \
           ranger \
           cryfs \
           tig \
           fzf \
           aspell \
           node \
           sbcl \
           rustup-init \
           rlwrap \
           weechat \
           docker \
           docker-machine \
           rsync \
           syncthing \
           youtube-dl

tw_log "Installing rest of the packages..."
tw_execute brew install --cask \
           alacritty \
           emacs \
           google-chrome \
           homebrew/cask-versions/firefox-developer-edition \
           keepassxc \
           authy \
           postman \
           mounty \
           balenaetcher \
           google-backup-and-sync \
           transmission \
           tunnelbear \
           remember-the-milk \
           dynalist \
           discord \
           element \
           kid3 \
           gimp \
           darktable \
           handbrake \
           xnviewmp \
           clementine \
           vlc \
           kodi \
           steam \
           origin \
           sony-ps4-remote-play \
           barrier \
           blender \
           obs \
           licecap \
           keycastr \
           libreoffice \
           virtualbox \
           diffmerge \
           razer-synapse \
           font-open-sans \
           font-inconsolata \
           font-liberation \
           font-roboto-mono \
           font-fira-code \
           nomachine \
           edex-ui

# Manual packages
# - Install pCloud Drive from https://www.pcloud.com
# - Install Audacity from https://www.fosshub.com/Audacity.html/audacity-macos-2.2.0.dmg
# - Install LAME and FFMPEG from https://lame.buanzo.org/#lameosx64bitdl
# - Install Razer Synapse drivers from http://rzr.to/synapse-mac-download

# Missing packages
# - GameHub
# - Droid Sans

# Inbuilt packages
# - Git
