#!/usr/bin/env bash

. "${mt_setup_dir}/mac/tasks"

tw_log "Setting up macOS..."

tw_log "Enabling hidden files in Finder..."
tw_execute defaults write com.apple.Finder AppleShowAllFiles YES
tw_execute killall Finder

. "${mt_setup_dir}/mac/setup-sources"
. "${mt_setup_dir}/mac/install-packages"

tw_log "Setting up Docker..."
tw_execute docker-machine create --driver virtualbox default
tw_execute eval $(docker-machine env default)

tw_log "Changing shell to fish..."
tw_execute_eval "echo \"/usr/local/bin/fish\" | sudo tee -a /etc/shells"
tw_execute chsh -s /usr/local/bin/fish

tw_log "Setting up Rust..."
tw_execute rustup-init

tw_confirm "Setup startup services?" \
           mt_task_mac_setup_startup_services \
           "Setting up of startup services skipped."

tw_log "Steps for macOS complete!"
