#!/usr/bin/env bash

tw_log "Setting up macOS..."

tw_log "Enabling hidden files in Finder..."
tw_execute defaults write com.apple.Finder AppleShowAllFiles YES
tw_execute killall Finder

. "${mt_setup_dir}/mac/setup-sources"
. "${mt_setup_dir}/mac/install-packages"

tw_log "Changing shell to fish..."
tw_execute echo "/usr/local/bin/fish" | sudo tee -a /etc/shells
tw_execute chsh -s /usr/local/bin/fish

tw_log "Setting up Rust..."
tw_execute rustup-init
