#!/usr/bin/env bash

mt_log "Setting up Mac..."

mt_log "Taking care of a few things..."
defaults write com.apple.Finder AppleShowAllFiles YES
killall Finder

. ~/.setup/mac/install-packages

mt_log "Changing shell to fish..."
echo "/usr/local/bin/fish" | sudo tee -a /etc/shells
chsh -s /usr/local/bin/fish

mt_log "Taking care of a few final things..."
rustup-init
