#!/usr/bin/env bash

command=${1}
arguments=${@:2}

case "${command}" in
    zip)
        zip -r "${2}.zip" $arguments
        ;;

    unzip)
        unzip "${arguments}"
        ;;

    tar)
        tar -cvzf "${2}.tar.gz" $arguments
        ;;

    untar)
        tar -xvzf "${arguments}"
        ;;

    ungzip)
        gz -dk "${arguments}"
        ;;

    unrar)
        unrar e "${arguments}"
        ;;

    un7zip)
        7zip e "${arguments}"
        ;;

    *)
        echo "Not implemented!"
        ;;
esac
