#!/usr/bin/env bash

if [ "${1}" ]; then
    mt_value="${1}"
else
    mt_value=$(echo -e "100\n90\n80\n70\n60\n50\n40\n30\n20\n10" | rofi -dmenu)
fi

case "${mt_value=}" in
    100)
        mt_brightness=1.0
        ;;

    90)
        mt_brightness=0.9
        ;;

    80)
        mt_brightness=0.8
        ;;

    70)
        mt_brightness=0.7
        ;;

    60)
        mt_brightness=0.6
        ;;

    50)
        mt_brightness=0.5
        ;;

    40)
        mt_brightness=0.4
        ;;

    30)
        mt_brightness=0.3
        ;;

    20)
        mt_brightness=0.2
        ;;

    10)
        mt_brightness=0.1
        ;;

    *)
        mt_brightness=0.5
        ;;
esac

xrandr --output "eDP1" --brightness ${mt_brightness}
echo "Brightness set to ${mt_brightness}"
