#!/usr/bin/env bash

# Disable charge thresholds temporarily
mt-battery-charge-thresholds-set 96 100

# Wait for user input
read -n1 -r -p "Press any key when ready to stop charging..."

# Set charge thresholds again
mt-battery-charge-thresholds-set $1 $2
