#!/usr/bin/env bash

# Abort for Wayland
if [ "$XDG_SESSION_TYPE" == "wayland" ]; then
    notify-send "Not implemented for Wayland!"
    echo "Not implemented for Wayland!"
    exit 1
fi

# Detect display and set prompter
. ~/.assets/libs/bash/select-prompter

# Prompt for a choice
mt_response=$(echo -e "Auto (3840x2160)\nMedium (2560x1440)\nLow (1920x1080)\nPrimary => External\nExternal <= Primary" | ${mt_prompter})

# Gather devices info
xrandr_devices=$(xrandr)

# Detect primary display
primary_display=$(sbcl --script ~/.assets/parsers/xrandr-parser.lisp primary $(xrandr))

# Execute the appropriate command based on choice
case "${mt_response}" in
    "Auto (3840x2160)")
        xrandr --output "${primary_display}" --auto --output "HDMI-0" --off
        ;;

    "Medium (2560x1440)")
        xrandr --output "${primary_display}" --mode 2560x1440 --output "HDMI-0" --off
        ;;

    "Low (1920x1080)")
        xrandr --output "${primary_display}" --mode 1920x1080 --output "HDMI-0" --off
        ;;

    "Primary => External")
        xrandr --output "${primary_display}" --auto --output "HDMI-0" --auto --right-of "${primary_display}"
        ;;

    "External <= Primary")
        xrandr --output "${primary_display}" --auto --output "HDMI-0" --auto --left-of "${primary_display}"
        ;;

    *)
        # Ignore
        ;;
esac
