#!/usr/bin/env bash

# Abort for Wayland
if [ "$XDG_SESSION_TYPE" == "wayland" ]; then
    mt_message="Not implemented for Wayland!"
    notify-send "${mt_message}"
    echo ${mt_message}
    exit 1
fi

# Detect display and set prompter
. ~/.assets/libs/bash/select-prompter

# Prompt for a choice
mt_response=$(echo -e "normal\nleft\nright\ninverted" | ${mt_prompter})

# Gather devices info
xrandr_devices=$(xrandr)

# Detect primary display
primary_display=$(sbcl --script ~/.assets/parsers/xrandr-parser.lisp primary $(xrandr))

# Rotate the screen based on selection
xrandr --output "${primary_display}" --rotate "${mt_response}"
