#!/usr/bin/env bash

case "${1}" in
    x | x11 | xorg)
        startx ~/.xinitrc
        ;;

    *)
        XDG_SESSION_TYPE=wayland dbus-run-session sway -c ~/.config/wm/sway
        ;;
esac

echo -e "\n\nPower-off or Reboot the machine?"
echo -e "Power-off (s|p|o)"
echo -e "Reboot (r)"
read -n 1 -s user_input
case "$user_input" in
    [sSpPoO])
        mt-power-mode shutdown
        ;;

    [rR])
        mt-power-mode reboot
        ;;
esac
