#!/usr/bin/env bash

case "${1}" in
    x | x11 | xorg)
        startx ~/.xinitrc
        ;;

    *)
        XDG_SESSION_TYPE=wayland dbus-run-session sway -c ~/.config/wm/sway
        ;;
esac

echo -e "\n\nPower-off the machine? (Y/n)"
read -n 1 -s user_input
case "$user_input" in
    [yY])
        mt-power-mode shutdown
        ;;
esac
