#!/usr/bin/env bash

# Detect display and set prompter
. ~/.assets/libs/bash/select-prompter

if [ "${1}" ]; then
    mt_mode="${1}"
else
    mt_mode=$(echo -e "intel\nhybrid\nnvidia" | ${mt_prompter})
fi

case "${mt_mode}" in
    i | integrated | intel )
        echo "Switching to integrated GPU..."
        optimus-manager --switch intel --no-confirm
        ;;

    o | h | hybrid )
        echo "Switching to hybrid mode..."
        optimus-manager --switch hybrid --no-confirm
        ;;

    p | d | dedicated | n | nvidia )
        echo "Switching to dedicated GPU..."
        optimus-manager --switch nvidia --no-confirm
        ;;

    *)
        echo "Option not specified"
        ;;
esac
