#!/usr/bin/env bash

# Abort for Wayland
if [ "$XDG_SESSION_TYPE" == "wayland" ]; then
    mt_message="Not implemented for Wayland!"
    notify-send "${mt_message}"
    echo ${mt_message}
    exit 1
fi

# Detect display and set prompter
. ~/.assets/libs/bash/select-prompter

# Check for supplied argument
if [ "${1}" ]; then
    # Use the supplied argument
    mt_mode="${1}"
else
    # Prompt for a value
    mt_mode=$(echo -e "intel\nhybrid\nnvidia" | ${mt_prompter})
fi

# Execute the appropriate command based on choice
case "${mt_mode}" in
    i | integrated | intel )
        echo "Switching to integrated GPU..."
        optimus-manager --switch intel --no-confirm
        ;;

    o | h | hybrid )
        echo "Switching to hybrid mode..."
        optimus-manager --switch hybrid --no-confirm
        ;;

    p | d | dedicated | n | nvidia )
        echo "Switching to dedicated GPU..."
        optimus-manager --switch nvidia --no-confirm
        ;;

    *)
        echo "Option not specified"
        ;;
esac
