#!/usr/bin/env bash

# Detect display and set prompter
. ~/.assets/libs/bash/select-prompter

# Prompt for a choice
mt_menu=$(echo -e "display orientation\nbluetooth\nbrightness\ncolor-temperature\nproject screen\ngpu" | ${mt_prompter})

# Spawn the appropriate menu based on choice
case "${mt_menu}" in
    "display orientation")
        mt-display-orientation
        ;;

    "bluetooth")
        mt-bluetooth
        ;;

    "brightness")
        mt-brightness-mode
        ;;

    "color-temperature")
        mt-color-temperature-mode
        ;;

    "project screen")
        mt-display-mode
        ;;

    "gpu")
        mt-gpu-mode
        ;;

    *)
        echo "Not implemented!"
        ;;
esac
