#!/usr/bin/env bash

# Detect display and set prompter
. ~/.assets/libs/bash/select-prompter

# Prompt for a choice
mt_menu=$(echo -e "bluetooth\nbrightness\ncolor-temperature\ndisplay orientation\nrestart network" | ${mt_prompter})

# Spawn the appropriate menu based on choice
case "${mt_menu}" in
    "bluetooth")
        mt-bluetooth-devices
        ;;

    "brightness")
        mt-display-brightness-set
        ;;

    "color-temperature")
        mt-display-color-temperature-switch
        ;;

    "display orientation")
        mt-display-orientation-switch
        ;;

    "restart network")
        mt-network-reset
        ;;

    *)
        echo "Not implemented!"
        ;;
esac
