#!/usr/bin/env bash

# Detect display and set prompter
. ~/.assets/libs/bash/select-prompter

mt_menu=$(echo -e "brightness\ndisplay\ngpu\nbluetooth" | ${mt_prompter})

case "${mt_menu}" in
    "brightness")
        mt-brightness-mode
        ;;

    "display")
        mt-display-mode
        ;;

    "gpu")
        mt-gpu-mode
        ;;

    "bluetooth")
        mt-bluetooth
        ;;

    *)
        echo "Not implemented!"
        ;;
esac
