#!/usr/bin/env bash

if [[ $# -lt 2 ]]; then
    echo "Usage: mt-media <operation> <device> [path]"
    exit 1
fi

case "${1}" in
    m | mount)
        if [[ $# -lt 3 ]]; then
            echo "Usage: mt-media (m|mount) <device> <path>"
            exit 1
        fi

        # Create media directory for user
        sudo mkdir /run/media/${USER}/$3

        # Grant permission to user
        sudo chown ${USER}:${USER}  /run/media/${USER}/$3

        # Mount the media
        sudo mount $2 /run/media/${USER}/$3
        ;;

    u | unmount)
        if [[ $# -lt 3 ]]; then
            echo "Usage: mt-media (m|mount) <device> <path>"
            exit 1
        fi

        # Unmount media
        sudo umount $2

        # Remove user directory
        sudo rm -rf /run/media/${USER}/$3
        ;;

    p | poweroff | r | remove)
        udisksctl power-off -b $2
        ;;

    a | analyze )
        sudo smartctl -A -d sat $2
        ;;

    *)
        echo "Not implemented!"
        ;;
esac
