#!/usr/bin/env bash

. ~/.assets/libs/bash/detect-init-system

if [ "${1}" ]; then
    mt_mode="${1}"
else
    mt_mode=$(echo -e "lock\nindoor\noutdoor\nquit\nsuspend\nhibernate\nshutdown\nrestart\nawake\nsleepy" | rofi -dmenu)
fi

# Function to switch power using systemd
switch-power-mode-with-systemd () {
    case "${mt_mode}" in
        "lock")
            mt-lock-desktop
            ;;

        "indoor")
            mt-lock-disable
            ;;

        "outdoor")
            mt-lock-enable
            ;;

        "quit")
            i3-msg exit
            ;;

        "sleep" | "suspend")
            systemctl suspend
            ;;

        "hibernate")
            systemctl hibernate
            ;;

        "shutdown" | "poweroff")
            systemctl poweroff
            ;;

        "restart" | "reboot")
            systemctl reboot
            ;;

        "awake")
            systemctl mask sleep.target suspend.target
            ;;

        "sleepy")
            systemctl unmask sleep.target suspend.target
            ;;

        *)
            echo "Not implemented!"
            ;;
    esac
}

# Function to switch power using runit
switch-power-mode-with-runit () {
    case "${mt_mode}" in
        "lock")
            mt-lock-desktop
            ;;

        "indoor")
            mt-lock-disable
            ;;

        "outdoor")
            mt-lock-enable
            ;;

        "quit")
            i3-msg exit
            ;;

        "sleep" | "suspend")
            loginctl suspend
            ;;

        "hibernate")
            loginctl hibernate
            ;;

        "shutdown" | "poweroff")
            loginctl poweroff
            ;;

        "restart" | "reboot")
            loginctl reboot
            ;;

        "awake")
            echo "Not implemented!"
            ;;

        "sleepy")
            echo "Not implemented!"
            ;;

        *)
            echo "Not implemented!"
            ;;
    esac
}

case "${tw_init_system}" in
    SystemD)
        switch-power-mode-with-systemd
        ;;

    Runit)
        switch-power-mode-with-runit
        ;;

    *)
        echo "Not implemented!"
        ;;
esac
