#!/usr/bin/env bash

# Detect display and set prompter
. ~/.assets/libs/bash/select-prompter

# Detect init system
. ~/.assets/libs/bash/detect-init-system

# Check for supplied argument
if [ "${1}" ]; then
    # Use the supplied argument
    mt_mode="${1}"
else
    # Prompt for a choice
    mt_mode=$(echo -e "lock\nindoor\noutdoor\nquit\nsuspend\nhibernate\nshutdown\nrestart\nawake\nsleepy" | ${mt_prompter})
fi

# Function to switch power using systemd
switch-power-mode-with-systemd () {
    case "${mt_mode}" in
        "lock")
            mt-session-lock-desktop
            ;;

        "indoor")
            mt-session-lock disable
            ;;

        "outdoor")
            mt-session-lock enable
            ;;

        "quit")
            mt-session-quit
            ;;

        "sleep" | "suspend")
            systemctl suspend
            ;;

        "hibernate")
            systemctl hibernate
            ;;

        "shutdown" | "poweroff")
            systemctl poweroff
            ;;

        "restart" | "reboot")
            systemctl reboot
            ;;

        "awake")
            systemctl mask sleep.target suspend.target
            ;;

        "sleepy")
            systemctl unmask sleep.target suspend.target
            ;;

        *)
            echo "Not implemented!"
            ;;
    esac
}

# Function to switch power using runit
switch-power-mode-with-runit () {
    case "${mt_mode}" in
        "lock")
            mt-session-lock-desktop
            ;;

        "indoor")
            mt-session-lock disable
            ;;

        "outdoor")
            mt-session-lock enable
            ;;

        "quit")
            mt-session-quit
            ;;

        "sleep" | "suspend")
            loginctl suspend
            ;;

        "hibernate")
            loginctl hibernate
            ;;

        "shutdown" | "poweroff")
            loginctl poweroff
            ;;

        "restart" | "reboot")
            loginctl reboot
            ;;

        "awake")
            echo "Not implemented!"
            ;;

        "sleepy")
            echo "Not implemented!"
            ;;

        *)
            echo "Not implemented!"
            ;;
    esac
}

# Use the appropriate implement based on the active init system
case "${mt_init_system}" in
    SystemD)
        switch-power-mode-with-systemd
        ;;

    Runit)
        switch-power-mode-with-runit
        ;;

    *)
        echo "Not implemented!"
        ;;
esac
