#!/usr/bin/env bash

# Detect display and set prompter
. ~/.assets/libs/bash/select-prompter

# Detect init system
. ~/.assets/libs/bash/detect-init-system

# Check for supplied argument
if [ "${1}" ]; then
    # Use the supplied argument
    mt_mode="${1}"
else
    # Prompt for a choice
    mt_mode=$(echo -e "lock\nindoor\noutdoor\nquit\nsuspend\nhibernate\nshutdown\nrestart" | ${mt_prompter})
fi

# Determine appropriate session controller
case "${mt_init_system}" in
    SystemD)
        SESSION_CONTROLLER=systemctl
        ;;

    Runit)
        SESSION_CONTROLLER=loginctl
        ;;
esac

# Execute the appropriate command
case "${mt_mode}" in
    "lock")
        mt-session-lock-now
        ;;

    "indoor")
        mt-session-lock-switch disable
        ;;

    "outdoor")
        mt-session-lock-switch enable
        ;;

    "quit")
        mt-session-quit
        ;;

    "sleep" | "suspend")
        $SESSION_CONTROLLER suspend
        ;;

    "hibernate")
        $SESSION_CONTROLLER hibernate
        ;;

    "shutdown" | "poweroff")
        notify-send "Power-off has been disabled from within a graphical session." --urgency=low
        # $SESSION_CONTROLLER poweroff
        ;;

    "restart" | "reboot")
        notify-send "Reboot has been disabled from within a graphical session." --urgency=low
        # $SESSION_CONTROLLER reboot
        ;;

    *)
        echo "Not implemented!"
        ;;
esac
