#!/usr/bin/env bash

if [[ $# -lt 1 ]]; then
    echo "Usage: mt-session-lock <enable/disable>"
    exit 1
fi

case "${1}" in
    enable | activate)
        # Start xss-lock
        xss-lock --transfer-sleep-lock -- mt-session-lock-desktop --nofork &
        ;;

    disable | deactivate)
        # Disable session lock
        killall xss-lock
        ;;

    *)
        echo "Not implemented!"
        ;;
esac
