#!/usr/bin/env bash

if [ "$XDG_SESSION_TYPE" == "wayland" ]; then
    fd . ~/_store/Vault-Mobile/media/wallpapers/ -t f -0 | shuf -n1 -z | xargs -0 swaybg -m fill -i
else
    fd . ~/_store/Vault-Mobile/media/wallpapers/ -t f -0 | shuf -n1 -z | xargs -0 feh --bg-fill
fi
