#!/usr/bin/env bash

WALLPAPERS_DIR=~/_store/Vault-Mobile/media/wallpapers/

if [ "$XDG_SESSION_TYPE" == "wayland" ]; then
    fd . $WALLPAPERS_DIR -t f -0 | shuf -n1 -z | xargs -0 swaybg -m fill -i
else
    fd . $WALLPAPERS_DIR -t f -0 | shuf -n1 -z | xargs -0 feh --bg-fill
fi
