#!/usr/bin/env bash

# TODO: (entering-the-void) Add Nvidia-legacy packages to the list
mt_packages=()

if [ "${1}" = "uninstall" ]; then
    sudo xbps-remove -Ry "${mt_packages[@]}"
else
    sudo xbps-install -Sy "${mt_packages[@]}"
fi
