#!/usr/bin/env bash

mt_packages=(nvidia390 nvidia390-libs-32bit)

if [ "${1}" = "uninstall" ]; then
    sudo xbps-remove -Ry "${mt_packages[@]}"
else
    sudo xbps-install -Sy "${mt_packages[@]}"
fi
