#!/usr/bin/env bash

# This script is an add-on to `~/.setup/start` containing device-specific setup
# for 2020 Lenovo ThinkPad X1 Extreme and mostly follows steps from
# https://wiki.archlinux.org/index.php/Lenovo_ThinkPad_X1_Extreme

# Install wireless drivers
sudo apt install firmware-iwlwifi -y

# Set display scaling for HiDPI
echo "Xft.dpi: 192" > ~/.Xresources
echo "[X11]
EnableHiDPI=true
[Wayland]
EnableHiDPI=true" | sudo tee /etc/sddm.conf

# Install Nvidia drivers
. ~/.setup/linux/other/nvidia-latest

# Fix audio input and output
sudo apt install firmware-sof-signed -y

# Enable Dolby Atmos Effect through pulseeffects
sudo apt install pulseeffects -y
pulseeffects
bash -c "$(curl -fsSL https://raw.githubusercontent.com/JackHack96/PulseEffects-Presets/pulseeffects/install.sh)"

# Improve touchpad experience with xinput
sudo apt install xinput -y
echo "
xinput set-prop 'SynPS/2 Synaptics TouchPad' 'libinput Accel Speed' 0.5
xinput set-prop 'SynPS/2 Synaptics TouchPad' 'libinput Click Method Enabled' 0 1
xinput set-prop 'SynPS/2 Synaptics TouchPad' 'libinput Tapping Enabled' 1
xinput set-prop 'SynPS/2 Synaptics TouchPad' 'libinput Natural Scrolling Enabled' 1
" > ~/.device-startup-tweaks

# Install tlp and more for power management
sudo apt install tlp acpi-call-dkms powertop -y
~/.bin/linux/mt-battery-set-charge-thresholds
systemctl enable tlp
systemctl start tlp

# TODO: Fix display scaling

# TODO: Fix display flickering on integrated mode

# TODO: Utilize fingerprint sensor
