#!/usr/bin/env bash

# This script is an add-on to `~/.setup/forge-config.lisp` containing
# device-specific setup for 2017 Lenovo ThinkPad X1 Carbon and mostly follows
# steps from https://wiki.archlinux.org/title/Laptop/Lenovo

# Configure startup sound volume
. ~/.setup/hardware/configure-default-sound-volume 70%

# Configure default screen brightness
. ~/.setup/hardware/configure-default-display-brightness 30%

# Improve touchpad experience
. ~/.setup/hardware/configure-touchpad-for-xorg "Synaptics TM3289-002" 0.75
. ~/.setup/hardware/configure-touchpad-for-wayland "2:7:Synaptics TM3289-002" 1

# Install tlp and more for power management
. ~/.setup/hardware/void/configure-power-management tlp acpi_call-dkms powertop

# Configure fingerprint sensor
. ~/.setup/hardware/configure-fingerprints
