#!/usr/bin/env bash

# This script is an add-on to `~/.setup/forge-config.lisp` containing
# device-specific setup for 2018 Lenovo ThinkPad X280 and mostly follows steps
# from https://wiki.archlinux.org/title/Laptop/Lenovo

# Improve touchpad experience
. ~/.setup/hardware/configure-touchpad-for-xorg "Synaptics TM3381-002" 0.75
. ~/.setup/hardware/configure-touchpad-for-wayland "2:7:Synaptics TM3381-002"

# Install tlp and more for power management
. ~/.setup/hardware/void/configure-power-management tlp acpi_call-dkms powertop

# Configure fingerprint sensor
. ~/.setup/hardware/configure-fingerprints
