#!/usr/bin/env bash

# This script is an add-on to `~/.setup/forge-config.lisp` containing
# device-specific setup for 2008 Lenovo ThinkPad X301 and mostly follows steps
# from https://wiki.archlinux.org/title/Laptop/Lenovo

# Set display scaling for the smaller screen
. ~/.setup/hardware/configure-dpi-for-xorg 82
. ~/.setup/hardware/configure-dpi-for-wayland 0.85 LVDS-1

# Configure default screen brightness
. ~/.setup/hardware/configure-default-display-brightness 70%

# Configure startup sound volume
. ~/.setup/hardware/configure-default-sound-volume 70%

# Install tlp and more for power management
. ~/.setup/hardware/void/configure-power-management tlp acpi_call-dkms tp_smapi-dkms powertop

# Configure fingerprint sensor
. ~/.setup/hardware/configure-fingerprints
