#!/usr/bin/env bash

# This script is an add-on to `~/.setup/forge-config.lisp` containing
# device-specific setup for 2010 Lenovo ThinkPad X201 and mostly follows steps
# from https://wiki.archlinux.org/title/Lenovo_ThinkPad_X201

# Set display scaling for the smaller screen
. ~/.setup/hardware/configure-dpi-for-xorg 72
. ~/.setup/hardware/configure-dpi-for-wayland 0.75 LVDS-1

# Configure default screen brightness
. ~/.setup/hardware/configure-default-display-brightness 30%

# Configure startup sound volume
. ~/.setup/hardware/configure-default-sound-volume 70%

# Improve touchpad and trackpoint experience
. ~/.setup/hardware/configure-touchpad-for-xorg "SynPS/2 Synaptics TouchPad" 0.5
. ~/.setup/hardware/configure-trackpoint-for-xorg "TPPS/2 IBM TrackPoint" 1
. ~/.setup/hardware/configure-touchpad-for-wayland "2:7:SynPS/2_Synaptics_TouchPad"
. ~/.setup/hardware/configure-trackpoint-for-wayland "2:10:TPPS/2_IBM_TrackPoint"

# Install tlp and more for power management
. ~/.setup/hardware/void/configure-power-management tlp acpi_call-dkms tp_smapi-dkms powertop

# Configure fingerprint sensor
. ~/.setup/hardware/configure-fingerprints
