#!/usr/bin/env bash

# This script is an add-on to `~/.setup/forge-config.lisp` containing
# device-specific setup for 2021 Lenovo ThinkPad P14s Gen 2 and mostly follows
# steps from https://wiki.archlinux.org/title/Laptop/Lenovo

# Fix audio input and output
sudo xbps-install -Sy sof-firmware

# Configure default screen brightness
. ~/.setup/hardware/configure-default-display-brightness 30%

# Install Nvidia drivers
. ~/.setup/hardware/void/nvidia-latest

# Configure startup sound volume
. ~/.setup/hardware/configure-default-sound-volume 70%

# Improve touchpad experience
. ~/.setup/hardware/configure-touchpad-for-xorg "SynPS/2 Synaptics TouchPad" 1.0
. ~/.setup/hardware/configure-trackpoint-for-xorg "TPPS/2 Elan TrackPoint" 1
. ~/.setup/hardware/configure-touchpad-for-wayland "2:7:SynPS/2_Synaptics_TouchPad" 1
. ~/.setup/hardware/configure-trackpoint-for-wayland "2:10:TPPS/2_Elan_TrackPoint" 1

# Install tlp and more for power management
. ~/.setup/hardware/void/configure-power-management tlp acpi_call-dkms powertop

# Configure fingerprint sensor
. ~/.setup/hardware/configure-fingerprints
