#!/usr/bin/env bash

# This script is an add-on to `~/.setup/forge-config.lisp` containing
# device-specific setup for 2020 Lenovo ThinkPad X1 Extreme and mostly follows
# steps from https://wiki.archlinux.org/index.php/Lenovo_ThinkPad_X1_Extreme

# Set display scaling for HiDPI
. ~/.setup/hardware/configure-dpi-for-xorg 192
. ~/.setup/hardware/configure-dpi-for-wayland 2 LVDS-1

# Install Nvidia drivers
. ~/.setup/hardware/void/nvidia-latest

# Fix audio input and output
sudo xbps-install -Sy alsa-firmware sof-firmware
echo "
pcm.!default {
  type hw
  card 1
}
ctl.!default {
  type hw
  card 1
}
" > .asoundrc

# Enable Dolby Atmos Effect through pulseeffects
. ~/.setup/hardware/void/configure-pulseeffects

# Improve touchpad experience
. ~/.setup/hardware/configure-touchpad-for-xorg "Synaptics TM3625-010" 1.0
. ~/.setup/hardware/configure-touchpad-for-wayland "2:7:Synaptics TM3625-010"

# Install tlp and more for power management
. ~/.setup/hardware/void/configure-power-management tlp acpi_call-dkms powertop

# TODO: Fix display scaling

# TODO: Fix display flickering on integrated mode

# Configure fingerprint sensor
. ~/.setup/hardware/configure-fingerprints
