#!/usr/bin/env bash

# This script is an add-on to `~/.setup/forge-config.lisp` containing
# device-specific setup for 2020 Lenovo ThinkPad T14 Gen 1 and mostly follows
# steps from https://wiki.archlinux.org/title/Laptop/Lenovo

# Fix audio input and output
sudo xbps-install -Sy sof-firmware

# Configure default screen brightness
. ~/.setup/hardware/configure-default-display-brightness 30%

# Install Nvidia drivers
. ~/.setup/hardware/void/nvidia-latest

# Configure startup sound volume
. ~/.setup/hardware/configure-default-sound-volume 70%

# Improve touchpad experience
. ~/.setup/hardware/configure-touchpad-for-xorg "Synaptics TM3471-020" 1.0
. ~/.setup/hardware/configure-trackpoint-for-xorg "TPPS/2 Elan TrackPoint" 0.5
. ~/.setup/hardware/configure-touchpad-for-wayland "1739:0:Synaptics_TM3471-020" 1
. ~/.setup/hardware/configure-trackpoint-for-wayland "2:10:TPPS/2_Elan_TrackPoint" 0.5

# Install tlp and more for power management
. ~/.setup/hardware/void/configure-power-management tlp acpi_call-dkms powertop

# Configure fingerprint sensor
. ~/.setup/hardware/configure-fingerprints
