#!/usr/bin/env bash

# This script is an add-on to `~/.setup/forge-config.lisp` containing
# device-specific setup for 2019 Lenovo ThinkPad X1 Carbon and mostly follows
# steps from https://wiki.archlinux.org/title/Laptop/Lenovo

# Fix audio input and output
sudo xbps-install -Sy sof-firmware

# Configure startup sound volume
. ~/.setup/hardware/configure-default-sound-volume 70%

# Improve touchpad experience
. ~/.setup/hardware/configure-touchpad-for-xorg "SYNA8004:00 06CB:CD8B Touchpad" 0.75
. ~/.setup/hardware/configure-touchpad-for-wayland "2:7:SYNA8004:00 06CB:CD8B Touchpad"

# Install tlp and more for power management
. ~/.setup/hardware/void/configure-power-management tlp acpi_call-dkms powertop

# Configure fingerprint sensor
. ~/.setup/hardware/configure-fingerprints
