#!/usr/bin/env bash

# Uninstall nouveau
sudo pacman -R xf86-video-nouveau --noconfirm

# Install latest Nvidia drivers
. ~/.setup/linux/other/nvidia-latest

# Install prime
sudo pacman -S nvidia-prime --noconfirm

# Install optimus-manager
paru -S optimus-manager optimus-manager-qt --noconfirm
