#!/usr/bin/env bash

mt_nvidia_packages=(nvidia \
                        nvidia-utils \
                        nvidia-settings \
                        lib32-nvidia-utils)

if [ "${1}" = "uninstall" ]; then
    sudo pacman -R "${mt_nvidia_packages[@]}" --noconfirm
else
    sudo pacman -S "${mt_nvidia_packages[@]}" --noconfirm
fi

# TODO: Implement installing additional 32-bit libraries for Nvidia
