#!/usr/bin/env bash

tw_log "Installing core packages..."
tw_execute sudo xbps-install -S \
           tmux \
           fish-shell \
           fd \
           exa \
           bat \
           ncdu \
           ripgrep \
           fzf \
           emacs \
           aspell \
           aspell-en \
           tig \
           ranger \
           xarchiver \
           htop \
           udisks2 \
           NetworkManager \
           bind-utils \
           weechat \
           docker \
           nodejs \
           rustup \
           brightnessctl \
           acpi \
           numlockx \
           neofetch \
           wget \
           openssh

tw_log "Installing graphical packages..."
tw_execute sudo xbps-install -S \
           picom \
           i3 \
           i3lock \
           xfce4 \
           feh \
           dmenu \
           rofi \
           kitty \
           udiskie \
           gparted \
           Thunar \
           gvfs \
           syncthing-gtk \
           firefox \
           chromium \
           keepassxc \
           evolution \
           transmission \
           virt-manager \
           libreoffice \
           blueman \
           shotwell \
           gimp \
           darktable \
           clementine \
           mpg123 \
           pavucontrol \
           gstreamer1 \
           pulseaudio \
           pulseeffects \
           audacity \
           easytag \
           vlc \
           handbrake \
           blender \
           youtube-dl \
           kodi \
           flameshot \
           obs \
           peek \
           steam \
           gamehub \
           barrier

tw_log "The following packages are absent on Void repos:"
tw_log "authy, postman, tunnelbear, rememberthemilk, dynalist, pcloud, balena-etcher, nomachine, edex-ui"

tw_log "Installing packages through flatpak..."
tw_execute ~/.scripts/linux/mt-flatpak-install discord com.discordapp.Discord

tw_log "Performing a few package-dependent configs..."
tw_execute sudo usermod -aG libvirt ismail
