#!/usr/bin/env bash

# Function to install peripheral drivers
mt_task_linux_install_peripherals_drivers () {
    tw_log "Installing packages for Razer devices..."

    # openrazer and razer-genie
    tw_execute sudo xbps-install -Sy \
               razergenie \
               openrazer-meta

    # Add current user to group 'plugdev'
    tw_execute sudo gpasswd -a $USER plugdev
}

# Function to setup startup services
mt_task_linux_setup_startup_services () {
    # Setup syncthing service
    # Taken care of by the script ~/.scripts/linux/startup/cli

    # Start libvirtd and virtlogd for virt-manager
    tw_execute sudo ln -s /etc/sv/libvirtd /var/service/
    tw_execute sudo ln -s /etc/sv/virtlogd /var/service/

    # Start bluetooth service
    tw_execute sudo ln -s /etc/sv/bluetoothd /var/service

    # Start ssh service
    tw_execute sudo ln -s /etc/sv/sshd /var/service
}

# Function to perform visual tweaks at GRUB and DM level
mt_task_linux_perform_visual_tweaks () {
    tw_log "Performing visual tweaks..."

    # Install GRUB Fallout theme
    tw_execute sudo xbps-install -Sy \
               unzip
    tw_execute_eval "wget -O - https://github.com/shvchk/fallout-grub-theme/raw/master/install.sh | bash"

    # Install sddm-slice theme
    tw_execute sudo xbps-install -Sy \
               qt5-graphicaleffects \
               fonts-roboto-ttf
    tw_execute sudo git clone \
               https://github.com/RadRussianRus/sddm-slice.git \
               /usr/share/sddm/themes/sddm-slice
    tw_execute_eval "echo \"[Theme]
Current=sddm-slice\" | sudo tee /etc/sddm.conf"
}
