#!/usr/bin/env bash

mt_log "Setting up Fedora..."

. ~/.setup/linux/fedora/setup-repos
. ~/.setup/linux/fedora/install-packages

mt_confirm_and_source "Create users?" \
                      ~/.setup/linux/create-users \
                      "Skipped creation of users"

mt_confirm_and_source "Setup GUI?" \
                      ~/.setup/linux/fedora/setup-gui \
                      "Skipped setting up of GUI"
