#!/usr/bin/env bash

mt_log "Setting up Fedora..."

. "$mt_setup_dir/linux/fedora/setup-sources"
. "$mt_setup_dir/linux/fedora/install-packages"

mt_confirm_and_source "Setup GUI?" \
                      "$mt_setup_dir/linux/fedora/setup-gui" \
                      "Skipped setting up of GUI"

mt_confirm_and_source "Setup Peripherals?" \
                      "$mt_setup_dir/linux/fedora/setup-peripherals" \
                      "Skipped setting up of peripherals"
