#!/usr/bin/env bash

mt_log "Setting up repos..."

mt_log "Installing RPM fusion repos..."
sudo dnf install -y \
     https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
     https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

mt_log "Adding additional package repos..."
sudo dnf copr enable evana/fira-code-fonts -y

mt_log "Updating all packages..."
sudo dnf update -y