#!/usr/bin/env bash

mt_log "Setting up GUI..."

mt_log "Installing display server..."
sudo dnf install -y \
     xorg-x11-server-Xorg \
     xorg-x11-apps \
     xorg-x11-init

mt_log "Installing graphics driver(s)..."
mt_log "Please choose your graphics card:"
mt_log "(1): AMD"
mt_log "(2): Intel"
mt_log "(3): Nvidia"
mt_prompt_for_character "" mt_temp

if [ "$mt_temp" == '1' ]; then
    graphics_driver="xorg-x11-drv-amdgpu"
elif [ "$mt_temp" == '2' ]; then
    graphics_driver="xorg-x11-drv-intel"
elif [ "$mt_temp" == '3' ]; then
    graphics_driver="xorg-x11-drv-nouveau"
else
    mt_log "Invalid option selected!"
fi

sudo dnf install -y \
     $graphics_driver \

mt_log "Installing a display manager..."
sudo dnf install sddm -y

mt_log "Activating display-manager service..."
sudo systemctl disable display-manager.service
sudo systemctl enable sddm

# TODO: Fix or verify
