#!/bin/bash

# Detect display and set prompter
. ~/.assets/libs/bash/select-prompter

# Prompt the user for a pattern
pattern_to_use=$(fabric -l | ${mt_prompter})

# Run fabric
fabric -y "$1" -s -p "$pattern_to_use"
