#!/usr/bin/env bash

start_time=$SECONDS

task_name="${1}"
topic="${2}"

if [[ -z "$task_name" ]]; then
    echo "Error: No task_name provided." >&2
    cat - 
    exit 1
fi

if [[ -z "$topic" ]]; then
    echo "Error: No ntfy topic provided." >&2
    cat - 
    exit 1
fi

cat - >&2

end_time=$SECONDS
exit_code=${PIPESTATUS[0]}

duration=$(( end_time - start_time ))
formatted_time=$(printf '%02dh:%02dm:%02ds\n' $((duration/3600)) $((duration%3600/60)) $((duration%60)))

if [[ $exit_code -eq 0 ]]; then
    status="SUCCESS"
    priority="default"
    tags="white_check_mark"
else
    status="FAILED (Code: $exit_code)"
    priority="high"
    tags="warning,x"
fi

curl -s \
     -H "Title: Task Finished" \
     -H "Tags: clock8" \
     -d "Task: $task_name
Status: $status
Duration: $formatted_time
Host: $(hostname)" \
     "https://ntfy.sh/$topic" > /dev/null
