#!/usr/bin/env bash

count=0
projects=`ls -A $1`

echo "Found $(ls -A $1 | wc -l) projects."

cd $1

for i in $projects;
do
    if [ -d $i ]
    then
        cd $i
        echo ""
        echo + $i
        git pull
        ((count++))
        cd ..;
    fi
done

echo ""
echo "Done updating" $count "projects."
echo ""
