#!/bin/bash

# Read input either from a file or from stdin
if [ -n "$1" ]; then
    # Read from file
    input=$(cat "$1")
else
    # Read from stdin
    input=$(cat -)
fi

# Run piper over the text
echo "$input" | ~/_store/Vault/binaries/piper/piper --model ~/_store/Vault/binaries/piper/voices/en_US-bryce-medium.onnx --output_file - | mpv -
