#!/usr/bin/env bash

SEARCH_DIR="$HOME/_store/"

CONFLICTS=$(fd -H .sync-conflict "$SEARCH_DIR")

show-message() {
    if [[ -n "$DISPLAY" ]]; then
        notify-send "$1" --urgency=low
    else
        echo "$1"
    fi
}

show-error() {
    if [[ -n "$DISPLAY" ]]; then
        notify-send "$1" --urgency=critical
    else
        echo "$1"
    fi
}

if [ -n "$CONFLICTS" ]; then
    COUNT=$(echo "$CONFLICTS" | wc -l)

    show-error "$COUNT conflict(s) found in $SEARCH_DIR"
else
    show-message "No Sync Conflict Found!"
fi
