#!/usr/bin/env bash

PIPER_DIR=~/_store/Vault/binaries/piper

if [ ! -t 0 ]; then
    # Read from stdin
    input=$(cat -)
elif [ $# -eq 0 ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    # Print accepted syntax
    echo -e "Please provide an input either as a file, arbitrary text, or through stdin.
Examples:
1) mt-speak ./filename.txt
2) mt-speak Hello! How are you?
3) echo \"Here, take this.\" | mt-speak"
    exit 0
elif [ -f "$1" ]; then
    # Read from specified file
    input=$(cat "$1")
else [ -n "$1" ];
     # Use the arbitrary text from argument
     input="$@"
fi

# Run piper over the input text
echo "$input" | $PIPER_DIR/piper --model $PIPER_DIR/voices/en_US-bryce-medium.onnx --output_file - | mpv -
