#!/bin/bash

if [ $# -eq 0 ]; then
    # Print accepted syntax
    echo -e "Please provide an input either as a file, arbitrary text, or through stdin.
Examples:
1) mt-speak ./filename.txt
2) mt-speak Hello!
3) echo \"Here, take this.\" | mt-speak"
    exit 0
elif [ -f "$1" ]; then
    # Read from specified file
    input=$(cat "$1")
elif [ -n "$1" ]; then
    # User the arbitrary text from argument
    input="$1"
else
    # Read from stdin
    input=$(cat -)
fi

# Run piper over the input text
echo "$input" | ~/_store/Vault/binaries/piper/piper --model ~/_store/Vault/binaries/piper/voices/en_US-bryce-medium.onnx --output_file - | mpv -
