#!/usr/bin/env bash

echo "
xinput set-prop '${1}' 'libinput Accel Speed' ${2}
xinput set-prop '${1}' 'libinput Click Method Enabled' 0 1
xinput set-prop '${1}' 'libinput Tapping Enabled' 1
xinput set-prop '${1}' 'libinput Natural Scrolling Enabled' 1
" > ~/.device-startup-tweaks2
