#!/usr/bin/env bash

count=0

cd $1

for i in `ls -A $1`;
do
    if [ -d $i ]
    then
        cd $i
        echo ""
        echo + $i
        git pull
        ((count++))
        cd ..;
    fi
done

echo ""
echo "Done updating" $count "projects"
echo ""
