#!/usr/bin/env bash

mt_nvidia_packages=(nvidia470 \
                        nvidia470-dkms \
                        nvidia470-libs \
                        nvidia470-libs-32bit \
                        nvidia470-gtklibs \
                        nvidia470-opencl)
mt_more_packages=(vulkan-loader \
                      vulkan-loader-32bit \
                      libgcc-32bit \
                      libstdc++-32bit \
                      libdrm-32bit \
                      libglvnd-32bit \
                      mesa-dri-32bit)

if [ "${1}" = "uninstall" ]; then
    sudo xbps-remove -Ry "${mt_nvidia_packages[@]}"
    sudo xbps-remove -Ry "${mt_more_packages[@]}"
else
    sudo xbps-install -Sy "${mt_nvidia_packages[@]}"
    sudo xbps-install -Sy "${mt_more_packages[@]}"
fi
