#!/usr/bin/env bash

# This script is an add-on to `~/.setup/forge-config.lisp` containing
# device-specific setup for 2016 Lenovo ThinkPad X260 and mostly follows steps
# from https://wiki.archlinux.org/title/Laptop/Lenovo

# Set display scaling for the smaller screen
. ~/.setup/hardware/configure-dpi-for-xorg 72
. ~/.setup/hardware/configure-dpi-for-wayland 0.75 LVDS-1

# Improve touchpad experience
. ~/.setup/hardware/configure-touchpad-for-xorg "SynPS/2 Synaptics TouchPad" 0.5
. ~/.setup/hardware/configure-touchpad-for-wayland "2:7:SynPS/2_Synaptics_TouchPad"

# Install tlp and more for power management
. ~/.setup/hardware/void/other/configure-power-management tlp acpi_call-dkms powertop

# Configure fingerprint sensor
. ~/.setup/hardware/configure-fingerprints
