#!/usr/bin/env bash

# This script is an add-on to `~/.setup/forge-config.lisp` containing
# device-specific setup for 2008 Lenovo ThinkPad T61p and mostly follows steps
# from https://wiki.archlinux.org/title/Laptop/Lenovo

# Improve touchpad experience with xinput
sudo xbps-install -Sy xinput # (Just in case)
. ~/.setup/hardware/enable-libinput-events-for-touchpad
. ~/.setup/hardware/configure-touchpad "SynPS/2 Synaptics TouchPad" 0.5

# Install tlp and more for power management
sudo xbps-install -Sy tlp tp_smapi-dkms powertop
~/.bin/linux/mt-battery-set-charge-thresholds
sudo ln -s /etc/sv/tlp /var/service

# TODO: Utilize fingerprint sensor
