#!/usr/bin/env bash

# This script is an add-on to `~/.setup/forge-config.lisp` containing
# device-specific setup for 2011 Lenovo ThinkPad X420s and mostly follows steps
# from https://wiki.archlinux.org/title/Lenovo_ThinkPad_T420s

# Set display scaling for the smaller screen
. ~/.setup/hardware/configure-dpi 82

# Improve touchpad experience for xorg
. ~/.setup/hardware/configure-touchpad-for-xorg "SynPS/2 Synaptics TouchPad" 0.5

# Install tlp and more for power management
sudo xbps-install -Sy tlp acpi_call-dkms tp_smapi-dkms powertop
~/.bin/linux/mt-battery-set-charge-thresholds
sudo ln -s /etc/sv/tlp /var/service

# Configure fingerprint sensor
. ~/.setup/hardware/configure-fingerprints
