#!/usr/bin/env bash

# This script is an add-on to `~/.setup/forge-config.lisp` containing
# device-specific setup for 2007 Lenovo ThinkPad X61s and mostly follows steps
# from https://wiki.archlinux.org/title/Laptop/Lenovo

# Set display scaling for the smaller screen
. ~/.setup/hardware/configure-dpi 72

# Install tlp and more for power management
. ~/.setup/hardware/void/other/configure-power-management tlp acpi_call-dkms tp_smapi-dkms powertop

# Configure fingerprint sensor
# TODO: Fix
. ~/.setup/hardware/configure-fingerprints
