#!/usr/bin/env bash

# This script is an add-on to `~/.setup/forge-config.lisp` containing
# device-specific setup for 2011 Lenovo ThinkPad X220 and mostly follows steps
# from https://wiki.archlinux.org/title/Lenovo_ThinkPad_X220

# Set display scaling for the smaller screen
. ~/.setup/hardware/configure-dpi 72

# Improve touchpad experience for xorg
. ~/.setup/hardware/configure-touchpad-for-xorg "SynPS/2 Synaptics TouchPad" 0.5

# Install tlp and more for power management
. ~/.setup/hardware/configure-power-management tlp acpi_call-dkms tp_smapi-dkms powertop

# Configure fingerprint sensor
# TODO: Fix
. ~/.setup/hardware/configure-fingerprints
