#!/usr/bin/env bash

# This script is an add-on to `~/.setup/forge-config.lisp` containing
# device-specific setup for 2020 Lenovo ThinkPad X1 Extreme and mostly follows
# steps from https://wiki.archlinux.org/index.php/Lenovo_ThinkPad_X1_Extreme

# Set display scaling for HiDPI
. ~/.setup/hardware/configure-dpi 192

# Install Nvidia drivers
. ~/.setup/hardware/void/other/nvidia-latest

# Fix audio input and output
sudo xbps-install -Sy alsa-firmware sof-firmware
echo "
pcm.!default {
  type hw
  card 1
}
ctl.!default {
  type hw
  card 1
}
" > .asoundrc

# Enable Dolby Atmos Effect through pulseeffects
sudo xbps-install -Sy pulseeffects-legacy
pulseeffects
bash -c "$(curl -fsSL https://raw.githubusercontent.com/JackHack96/PulseEffects-Presets/pulseeffects/install.sh)"

# Improve touchpad experience for xorg
. ~/.setup/hardware/configure-touchpad-for-xorg "Synaptics TM3625-010" 1.0

# Install tlp and more for power management
sudo xbps-install -Sy tlp acpi_call-dkms powertop
~/.bin/linux/mt-battery-set-charge-thresholds
sudo ln -s /etc/sv/tlp /var/service

# TODO: Fix display scaling

# TODO: Fix display flickering on integrated mode

# Configure fingerprint sensor
. ~/.setup/hardware/configure-fingerprints
