#!/usr/bin/env bash

# This script is an add-on to `~/.setup/forge-config.lisp` containing
# device-specific setup for 2016 Lenovo ThinkPad X260 and mostly follows steps
# from https://wiki.archlinux.org/title/Laptop/Lenovo

# Set display scaling for the smaller screen
# The below line is useless as it places the default value '96'
# but a slightly better value could be '72'
. ~/.setup/hardware/configure-dpi 96

# Improve touchpad experience for xorg
. ~/.setup/hardware/configure-touchpad-for-xorg "SynPS/2 Synaptics TouchPad" 0.5

# Install tlp and more for power management
. ~/.setup/hardware/configure-power-management tlp acpi_call-dkms powertop

# Configure fingerprint sensor
. ~/.setup/hardware/configure-fingerprints
