#!/usr/bin/env bash

# This script is an add-on to `~/.setup/start` containing device-specific setup
# for 2020 Lenovo ThinkPad X1 Extreme and mostly follows steps from
# https://wiki.archlinux.org/index.php/Lenovo_ThinkPad_X1_Extreme

# Set display scaling for HiDPI
echo "Xft.dpi: 192" > ~/.Xresources
echo "[X11]
EnableHiDPI=true
[Wayland]
EnableHiDPI=true" | sudo tee /etc/sddm.conf

# Install Nvidia drivers
. ~/.setup/linux/other/nvidia-latest

# Fix audio input and output
sudo xbps-install -Sy alsa-firmware sof-firmware
echo "
pcm.!default {
  type hw
  card 1
}
ctl.!default {
  type hw
  card 1
}
" > .asoundrc

# Enable Dolby Atmos Effect through pulseeffects
sudo xbps-install -Sy pulseeffects-legacy
pulseeffects
bash -c "$(curl -fsSL https://raw.githubusercontent.com/JackHack96/PulseEffects-Presets/pulseeffects/install.sh)"

# Improve touchpad experience with xinput
sudo xbps-install -Sy xinput # (Just in case)
sudo mkdir /etc/X11/xorg.conf.d # (Just in case)
echo "
Section \"InputClass\"
    Identifier \"libinput touchpad catchall\"
    MatchIsTouchpad \"on\"
    MatchDevicePath \"/dev/input/event*\"
    Driver \"libinput\"
EndSection
" | sudo tee /etc/X11/xorg.conf.d/40-libinput.conf
echo "
xinput set-prop 'SynPS/2 Synaptics TouchPad' 'libinput Accel Speed' 1.0
xinput set-prop 'SynPS/2 Synaptics TouchPad' 'libinput Click Method Enabled' 0 1
xinput set-prop 'SynPS/2 Synaptics TouchPad' 'libinput Tapping Enabled' 1
xinput set-prop 'SynPS/2 Synaptics TouchPad' 'libinput Natural Scrolling Enabled' 1
" > ~/.device-startup-tweaks

# Install tlp and more for power management
sudo xbps-install -Sy tlp acpi_call-dkms powertop
~/.bin/linux/mt-battery-set-charge-thresholds
sudo ln -s /etc/sv/tlp /var/service

# TODO: Fix display scaling

# TODO: Fix display flickering on integrated mode

# TODO: Utilize fingerprint sensor
