#!/usr/bin/env bash

# This script is an add-on to `~/.setup/start` containing device-specific setup
# for 2018 Lenovo ThinkPad X280 and mostly follows steps from
# https://wiki.archlinux.org/title/Laptop/Lenovo

# Improve touchpad experience with xinput
sudo xbps-install -Sy xinput # (Just in case)
sudo mkdir /etc/X11/xorg.conf.d # (Just in case)
echo "
Section \"InputClass\"
    Identifier \"libinput touchpad catchall\"
    MatchIsTouchpad \"on\"
    MatchDevicePath \"/dev/input/event*\"
    Driver \"libinput\"
EndSection
" | sudo tee /etc/X11/xorg.conf.d/40-libinput.conf
echo "
xinput set-prop 'Synaptics TM3381-002' 'libinput Accel Speed' 0.75
xinput set-prop 'Synaptics TM3381-002' 'libinput Click Method Enabled' 0 1
xinput set-prop 'Synaptics TM3381-002' 'libinput Tapping Enabled' 1
xinput set-prop 'Synaptics TM3381-002' 'libinput Natural Scrolling Enabled' 1
" > ~/.device-startup-tweaks

# Install tlp and more for power management
sudo xbps-install -Sy tlp acpi_call-dkms powertop
~/.bin/linux/mt-battery-set-charge-thresholds
sudo ln -s /etc/sv/tlp /var/service

# TODO: Utilize fingerprint sensor
