#!/usr/bin/env bash

# This script is an add-on to `~/.setup/forge-config.lisp` containing
# device-specific setup for 2019 Lenovo ThinkPad X1 Carbon and mostly follows
# steps from https://wiki.archlinux.org/title/Laptop/Lenovo

# Fix audio input and output
sudo xbps-install -Sy sof-firmware

# Improve touchpad experience with xinput
sudo xbps-install -Sy xinput # (Just in case)
. ~/.setup/hardware/enable-libinput-events-for-touchpad
. ~/.setup/hardware/configure-touchpad "SYNA8004:00 06CB:CD8B Touchpad" 0.75

# Install tlp and more for power management
sudo xbps-install -Sy tlp acpi_call-dkms powertop
~/.bin/linux/mt-battery-set-charge-thresholds
sudo ln -s /etc/sv/tlp /var/service

# Install Mesa Intel drivers
. ~/.setup/hardware/void/other/mesa

# Configure fingerprint sensor
. ~/.setup/hardware/configure-fingerprints
