#!/usr/bin/env bash

# This script is an add-on to `~/.setup/forge-config.lisp` containing
# device-specific setup for 2016 Lenovo ThinkPad X260 and mostly follows steps
# from https://wiki.archlinux.org/title/Laptop/Lenovo

# Set display scaling for the smaller screen
# The below line is useless as it places the default value '96'
# but a slightly better value could be '72'
. ~/.setup/hardware/enable-hidpi 96

# Improve touchpad experience with xinput
sudo xbps-install -Sy xinput # (Just in case)
. ~/.setup/hardware/enable-libinput-events-for-touchpad
. ~/.setup/hardware/configure-touchpad "SynPS/2 Synaptics TouchPad" 0.5

# Install tlp and more for power management
sudo xbps-install -Sy tlp acpi_call-dkms powertop
~/.bin/linux/mt-battery-set-charge-thresholds
sudo ln -s /etc/sv/tlp /var/service

# TODO: Utilize fingerprint sensor
