#!/usr/bin/env bash

# This script is an add-on to `~/.setup/forge-config.lisp` containing
# device-specific setup for 2008 Lenovo ThinkPad T61p and mostly follows steps
# from https://wiki.archlinux.org/title/Laptop/Lenovo

# Improve touchpad experience for xorg
. ~/.setup/hardware/configure-touchpad-for-xorg "SynPS/2 Synaptics TouchPad" 0.5

# Install tlp and more for power management
. ~/.setup/hardware/void/other/configure-power-management tlp acpi_call-dkms powertop

# Configure fingerprint sensor
. ~/.setup/hardware/configure-fingerprints
