#!/usr/bin/env bash

# This script is an add-on to `~/.setup/forge-config.lisp` containing
# device-specific setup for 2018 Lenovo ThinkPad X1 Yoga Gen 3 and mostly follows
# steps from https://wiki.archlinux.org/title/Lenovo_ThinkPad_X1_Yoga_(Gen_3)

# Improve touchpad experience for xorg
. ~/.setup/hardware/configure-touchpad-for-xorg "SynPS/2 Synaptics TouchPad" 0.75

# Install tlp and more for power management
. ~/.setup/hardware/configure-power-management tlp acpi_call-dkms powertop

# Set up orientation sensors
# TODO: Fix
sudo xbps-install -Sy iio-sensor-proxy
sudo ln -s /etv/sv/iio-sensor-proxy /var/service

# Configure fingerprint sensor
# TODO: Fix this
. ~/.setup/hardware/configure-fingerprints
