#!/usr/bin/env bash

mt_log "Creating users..."

sudo useradd -m -g users -s /bin/fish -c "Mohammed Ismail Ansari" ismail
sudo passwd ismail

mt_log "You still need to edit /etc/sudoers with 'visudo' command for this user to be able to run sudo commands."
