#!/usr/bin/env bash

# Add RPM Fusion repos
echo "Adding RPM fusion repos"
sudo dnf install -y \
     https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
     https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

# Update installed packages
echo "Updating all packages"
sudo dnf update -y

# Install packages from URLs
echo "Installing google-chrome"
sudo dnf install -y \
     https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
echo "Installing crossover from URL"
sudo dnf install -y \
     http://crossover.codeweavers.com/redirect/crossover.rpm

# Install rest of the packages
echo "Installing rest of the packages"
sudo dnf install -y \
     i3 \
     i3status \
     i3lock \
     feh \
     terminology \
     fish \
     emacs \
     pcmanfm \
     git \
     tig \
     npm \
     udisks \
     gparted \
     dropbox \
     syncthing \
     filezilla \
     transmission \
     thunderbird \
     youtube-dl \
     gstreamer \
     vlc \
     clementine \
     audacity \
     gimp \
     shotwell \
     kodi \
     openshot \
     easytag \
     steam \
     vokoscreen \
     key-mon \
     libreoffice \
     VirtualBox \
     docker \
     android-file-transfer \
     goldendict \
     aspell \
     aspell-en \
     calibre \
     rustfmt \
     cargo \
     levien-inconsolata-fonts \
     liberation-mono-fonts \
     google-roboto-mono-fonts \
     google-droid-sans-mono-fonts
sudo dnf copr enable evana/fira-code-fonts -y
sudo dnf install -y fira-code-fonts

# Manual packages
# - Install pCloud Drive from https://www.pcloud.com
# - Install MegaSync from https://mega.nz/sync
# - Install hyper from https://releases.hyper.is/download/rpm
# - Install postman from https://www.getpostman.com/downloads
# - Install Telegram
# - Install Discord
# - Install Remember The Milk
# - Install Dynalist

# Missing packages / Find alternative
# - Google Drive
# - licecap
# - Riot
# - Slack
# - Origin
# - Sony Remote play
# - TunnerBear
# - Spotify
# - Razer Synapse
# - Inconsolata

# Inbuilt packages
# (None yet)
