#!/usr/bin/env bash

tw_log "Installing core packages..."
tw_execute sudo pacman -S \
           polkit \
           tmux \
           fish \
           fd \
           exa \
           bat \
           ncdu \
           ripgrep \
           fzf \
           emacs \
           aspell \
           aspell-en \
           tig \
           ranger \
           xarchiver \
           htop \
           udisks2 \
           networkmanager \
           bind \
           docker \
           npm \
           rustup \
           brightnessctl \
           acpi \
           neofetch \
           wget \
           openssh

tw_log "Installing graphical packages..."
tw_execute sudo pacman -S \
           picom \
           i3 \
           xfce4 \
           feh \
           dmenu \
           rofi \
           alacritty \
           udiskie \
           gparted \
           thunar \
           gvfs \
           firefox-developer-edition \
           keepassxc \
           evolution \
           transmission-gtk \
           virtualbox \
           libreoffice-fresh \
           blueman \
           shotwell \
           gimp \
           darktable \
           clementine \
           mpg123 \
           pavucontrol \
           pavucontrol-qt \
           gstreamer \
           pulseaudio \
           pulseaudio-bluetooth \
           pulseeffects \
           audacity \
           easytag \
           vlc \
           handbrake \
           blender \
           youtube-dl \
           kodi \
           flameshot \
           obs-studio \
           peek \
           steam \
           ttf-opensans \
           ttf-inconsolata \
           ttf-liberation \
           ttf-roboto \
           ttf-roboto-mono \
           ttf-droid \
           ttf-fira-code \
           ttf-font-awesome

tw_log "Installing packages from AUR..."
tw_execute paru -S --mflags --skipinteg \
           gtk-theme-shades-of-gray \
           obsidian-icon-theme \
           bibata-cursor-theme \
           google-chrome \
           authy \
           postman-bin \
           tunnelbear \
           rememberthemilk \
           dynalist-desktop \
           discord \
           syncthing-gtk \
           pcloud-drive \
           gamehub \
           key-mon \
           balena-etcher \
           nomachine \
           systemd-numlockontty \
           edex-ui

# Manual packages
# (None yet)

# Missing packages / Find alternative
# - Google Drive
# - Origin
# - Sony Remote play
# - licecap
# - Razer Synapse

# Inbuilt packages
# (None yet)
