#!/usr/bin/env bash

# Install RPM Fusion repos
echo "Installing RPM fusion repos..."
sudo dnf install -y \
     https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
     https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

echo "Adding additional package repos..."
sudo dnf copr enable evana/fira-code-fonts -y

# Update installed packages
echo "Updating all packages..."
sudo dnf update -y

# Install packages from URLs
echo "Installing google-chrome..."
sudo dnf install -y \
     https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
echo "Installing crossover from URL..."
sudo dnf install -y \
     http://crossover.codeweavers.com/redirect/crossover.rpm

# Install rest of the packages
echo "Installing rest of the packages..."
sudo dnf install -y \
     i3 \
     i3status \
     i3lock \
     feh \
     terminology \
     fish \
     emacs \
     pcmanfm \
     git \
     tig \
     aspell \
     aspell-en \
     npm \
     rustfmt \
     cargo \
     udisks \
     gparted \
     syncthing \
     transmission \
     youtube-dl \
     thunderbird \
     audacity \
     easytag \
     gimp \
     shotwell \
     openshot \
     clementine \
     vlc \
     gstreamer \
     kodi \
     steam \
     gamehub \
     vokoscreen \
     key-mon \
     libreoffice \
     VirtualBox \
     docker \
     android-file-transfer \
     levien-inconsolata-fonts \
     liberation-mono-fonts \
     google-roboto-fonts \
     google-droid-sans-mono-fonts \
     fira-code-fonts

# Manual packages
# - Install hyper from https://releases.hyper.is/download/rpm
# - Install postman from https://www.getpostman.com/downloads
# - Install pCloud Drive from https://www.pcloud.com
# - Install Remember The Milk
# - Install Dynalist
# - Install Telegram
# - Install Discord

# Missing packages / Find alternative
# - Google Drive
# - TunnelBear
# - Slack
# - Origin
# - Sony Remote play
# - licecap
# - Razer Synapse

# Inbuilt packages
# (None yet)
