#!/usr/bin/env bash

tw_log "Installing packages..."

tw_log "Installing packages from official sources..."
tw_execute sudo pacman -S \
           picom \
           neofetch \
           i3 \
           dmenu \
           rofi \
           feh \
           terminology \
           fish \
           emacs \
           ranger \
           pcmanfm \
           xarchiver \
           firefox-developer-edition \
           tig \
           fzf \
           aspell \
           aspell-en \
           npm \
           rustup \
           udisks2 \
           udiskie \
           gparted \
           syncthing-gtk \
           transmission-gtk \
           keepassxc \
           keybase-gui \
           youtube-dl \
           thunderbird \
           audacity \
           easytag \
           gimp \
           shotwell \
           openshot \
           peek \
           mpg123 \
           clementine \
           vlc \
           gstreamer \
           kodi \
           steam \
           libreoffice-fresh \
           virtualbox \
           android-file-transfer \
           ttf-inconsolata \
           ttf-liberation \
           ttf-roboto \
           ttf-roboto-mono \
           ttf-droid \
           ttf-fira-code \
           ttf-font-awesome \
           --noconfirm

tw_log "Installing packages from AUR..."
tw_execute yay -S \
           hyper \
           google-chrome \
           authy \
           postman \
           tunnelbear \
           rememberthemilk \
           dynalist-desktop \
           discord \
           slack-desktop \
           pcloud-drive \
           gamehub \
           kazam \
           vokoscreen \
           key-mon \
           nomachine \
           --noconfirm

# Manual packages
# (None yet)

# Missing packages / Find alternative
# - Google Drive
# - Origin
# - Sony Remote play
# - licecap
# - Razer Synapse

# Inbuilt packages
# (None yet)

### More ###

# Install stable toolchain for rust
tw_execute rustup toolchain install stable
