#!/usr/bin/env bash

# Update all packages
echo "Updating all packages"
sudo pacman -Syu --noconfirm

# Install git
echo "Installing git"
sudo pacman -S git --noconfirm

# Install yay for AUR packages
echo "Installing yay for AUR packages"
mkdir temp
git clone https://aur.archlinux.org/yay.git ./temp/yay
cd ./temp/yay
makepkg -si
cd ../../
rm -rf ./temp

# Install required packages from official repos
echo "Installing packages from official repos"
sudo pacman -S \
     i3-wm \
     i3status \
     i3lock \
     feh \
     terminology \
     hyper \
     fish \
     emacs \
     pcmanfm \
     tig \
     aspell \
     aspell-en \
     npm \
     rustup \
     udisks2 \
     gparted \
     syncthing-gtk \
     transmission-gtk \
     youtube-dl \
     thunderbird \
     audacity \
     easytag \
     gimp \
     shotwell \
     openshot \
     clementine \
     vlc \
     gstreamer \
     kodi \
     steam \
     libreoffice-fresh \
     virtualbox \
     docker \
     android-file-transfer \
     ttf-inconsolata \
     ttf-liberation \
     ttf-roboto \
     ttf-roboto-mono \
     ttf-droid \
     ttf-fira-code \
     --noconfirm

# Install required packages from AUR
echo "Installing packages from AUR"
yay -S \
    google-chrome \
    postman \
    tunnelbear \
    rememberthemilk \
    dynalist-desktop \
    telegram-desktop \
    discord \
    slack-desktop \
    pcloud-drive \
    vokoscreen \
    key-mon \
    crossover \
    razergenie \
    --noconfirm

# Manual packages
# (None yet)

# Missing packages / Find alternative
# - Google Drive
# - Origin
# - Sony Remote play
# - licecap

# Inbuilt packages
# (None yet)

### More ###

# Install stable toolchain for rust
rustup toolchain install stable

echo "Setup complete for all package"
