#!/usr/bin/env bash

. "${mt_setup_dir}/linux/tasks"

tw_log "Setting up Arch Linux..."

tw_confirm "Set hostname?" \
           tw_task_set_hostname \
           "Setting of hostname skipped."

tw_confirm "Create users?" \
           tw_task_create_users \
           "Creation of users skipped."

tw_task_add_additional_software_sources

. "${mt_setup_dir}/linux/install-packages"

tw_log "Setting up Docker..."
tw_execute sudo groupadd docker
tw_execute sudo gpasswd -a ${USER} docker
tw_execute sudo systemctl enable docker

tw_log "Changing shell to fish..."
if ! [ "$(cat /etc/shells | grep "/usr/bin/fish")" ]; then
    tw_execute_eval "echo \"/usr/bin/fish\" | sudo tee -a /etc/shells"
fi
tw_confirm "Change user shell?" \
           tw_task_change_user_shell \
           "Changing of user shell skipped."

tw_log "Installing stable toolchain for Rust..."
tw_execute rustup toolchain install stable

tw_log "Setting up GUI..."
tw_task_setup_gui false

tw_confirm "Setup Nvidia graphics drivers?" \
           mt_task_install_nvidia_graphic_drivers \
           "Setting up of Nvidia drivers skipped."

tw_confirm "Setup peripherals drivers?" \
           mt_task_install_peripherals_drivers \
           "Setting up of periphericals drivers skipped."

tw_confirm "Setup startup services?" \
           mt_task_setup_startup_services \
           "Setting up of startup services skipped."
