#!/usr/bin/env bash

mt_log "Setting up Linux..."

mt_log "Detecting Linux type..."
if [ $(command -v apt) ]; then
    mt_abort_setup_for "Debian"
elif [ $(command -v dnf) ]; then
    . "$mt_setup_dir/linux/fedora/run"
elif [ $(command -v pacman) ]; then
    . "$mt_setup_dir/linux/arch/run"
else
    mt_abort_setup_for "an unknown"
fi

mt_confirm_and_source "Set hostname?" \
                      "$mt_setup_dir/linux/set-hostname" \
                      "Skipped setting of hostname"

mt_confirm_and_source "Create users?" \
                      "$mt_setup_dir/linux/create-users" \
                      "Skipped creation of users"

mt_confirm_and_source "Change shell?" \
                      "$mt_setup_dir/linux/change-shell" \
                      "Skipped changing of shell"

mt_prompt "Setup is complete, hit any key to reboot..."
sudo reboot 0
