#!/usr/bin/env bash

mt_log "Setting up Linux..."

mt_log "Detecting Linux type..."
if [ $(command -v apt) ]; then
    mt_abort_setup_for "Debian"
elif [ $(command -v dnf) ]; then
    . ~/.setup/linux/fedora/run
elif [ $(command -v pacman) ]; then
    . ~/.setup/linux/arch/run
else
    mt_abort_setup_for "an unknown"
fi

. ~/.setup/linux/change-shell
