#!/usr/bin/env bash

mt_log "Setting Nvidia graphics driver..."

sudo pacman -S \
     nvidia-390xx \
     nvidia-390xx-utils \
     nvidia-390xx-settings \
     lib32-nvidia-390xx-utils \
     lib32-opencl-nvidia-390xx \
     opencl-nvidia-390xx \
     --noconfirm
