#!/usr/bin/env bash

. "$1/lib" "$1"

mt_log "Setting up Linux..."

mt_log "Detecting Linux type..."
if [ $(command -v apt) ]; then
    mt_abort_setup_for "Debian"
elif [ $(command -v dnf) ]; then
    . "$mt_setup_dir/linux/fedora/run"
elif [ $(command -v pacman) ]; then
    . "$mt_setup_dir/linux/arch/run"
else
    mt_abort_setup_for "an unknown"
fi

mt_prompt "Setup is complete, hit any key to reboot..."
sudo reboot 0
