#!/usr/bin/env bash

mt_log "Setting up Linux..."

mt_log "Detecting Linux type..."
if [ $(command -v apt) ]; then
    mt_abort_setup_for "Debian"
elif [ $(command -v dnf) ]; then
    . ~/.setup/linux/install-packages-for-fedora
elif [ $(command -v pacman) ]; then
    . ~/.setup/linux/install-packages-for-arch
else
    mt_abort_setup_for "an unknown"
fi

mt_log "Changing shell to fish..."
chsh -s /bin/fish

mt_log "Setting up docker..."
sudo groupadd docker
sudo gpasswd -a $USER docker
sudo service docker restart
