#!/usr/bin/env bash

# Function to set up Docket
mt_task_linux_setup_docker () {
    tw_log "Setting up Docker..."
    tw_execute sudo groupadd docker
    tw_execute sudo gpasswd -a ${USER} docker
    tw_execute sudo systemctl enable docker
}

# Function to change user shell
mt_task_linux_change_user_shell () {
    tw_log "Changing shell to fish..."
    if ! [ "$(cat /etc/shells | grep "/usr/bin/fish")" ]; then
        tw_execute_eval "echo \"/usr/bin/fish\" | sudo tee -a /etc/shells"
    fi
    tw_task_change_user_shell
}

# Function to install toolchain for Rust
mt_task_linux_install_rust_toolchain() {
    tw_log "Installing stable toolchain for Rust..."
    tw_execute rustup toolchain install stable
}

# Function to set up GUI
mt_task_linux_setup_gui () {
    tw_log "Setting up GUI..."
    tw_task_setup_gui false
}

# Function to install peripheral drivers
mt_task_linux_install_peripherals_drivers () {
    tw_log "Installing packages for Razer devices..."
    # Install Razer drivers and polychromatic backend
    tw_execute paru -S \
               python-notify2 \
               openrazer-meta \
               polychromatic \
               --noconfirm
    # Install linux headers for dkms
    tw_execute sudo pacman -Syu \
               linux-headers \
               --noconfirm
    # Add current user to group 'plugdev'
    tw_execute sudo gpasswd -a $USER plugdev
}

# Function to setup startup services
mt_task_linux_setup_startup_services () {
    tw_log "Setting up startup services..."

    # Setup syncthing service
    tw_execute systemctl --user enable syncthing.service
    tw_execute systemctl --user start syncthing.service

    # Start network manager service
    tw_execute systemctl enable NetworkManager.service
    tw_execute systemctl start NetworkManager.service
}

# Function to perform visual tweaks at GRUB and DM level
mt_task_linux_perform_visual-tweaks () {
    tw_log "Performing visual tweaks..."

    # Install GRUB Fallout theme
    tw_execute sudo pacman -S\
               unzip \
               --noconfirm
    tw_execute_eval "wget -O - https://github.com/shvchk/fallout-grub-theme/raw/master/install.sh | bash"

    # Install sddm-slice theme
    tw_execute sudo pacman -S \
               qt5-graphicaleffects \
               ttf-roboto-mono \
               --noconfirm
    tw_execute sudo git clone \
               https://github.com/RadRussianRus/sddm-slice.git \
               /usr/share/sddm/themes/sddm-slice
    tw_execute_eval "echo \"[Theme]
Current=sddm-slice\" | sudo tee /etc/sddm.conf"
}
