#!/usr/bin/env bash

# Function to install proprietary Nvidia drivers
mt_task_install_nvidia_graphic_drivers () {
    tw_execute sudo pacman -S \
               nvidia-390xx \
               nvidia-390xx-utils \
               nvidia-390xx-settings \
               lib32-nvidia-390xx-utils \
               lib32-opencl-nvidia-390xx \
               opencl-nvidia-390xx \
               --noconfirm
}

# Function to install peripheral drivers
mt_task_install_peripherals_drivers () {
    tw_log "Installing packages for Razer devices..."
    # Install Razer drivers and polychromatic backend
    tw_execute yay -S \
               python-notify2 \
               openrazer-meta \
               polychromatic \
               --noconfirm
    # Install linux headers for dkms
    tw_execute sudo pacman -Syu \
               linux-headers \
               --noconfirm
    # Add current user to group 'plugdev'
    tw_execute sudo gpasswd -a $USER plugdev
}

# Function to setup startup services
mt_task_setup_startup_services () {
    tw_log "Setting up startup services..."

    # Setup syncthing service
    tw_execute systemctl --user enable syncthing.service
    tw_execute systemctl --user start syncthing.service
}
