#!/usr/bin/env bash

# Function to install peripheral drivers
mt_task_linux_install_peripherals_drivers () {
    tw_log "Installing packages for Razer devices..."
    # Install Razer drivers and polychromatic backend
    tw_execute paru -S \
               python-notify2 \
               openrazer-meta \
               polychromatic \
               --noconfirm
    # Install linux headers for dkms
    tw_execute sudo pacman -Syu \
               linux-headers \
               --noconfirm
    # Add current user to group 'plugdev'
    tw_execute sudo gpasswd -a $USER plugdev
}

# Function to setup startup services
mt_task_linux_setup_startup_services () {
    tw_log "Setting up startup services..."

    # Setup syncthing service
    tw_execute systemctl --user enable syncthing.service
    tw_execute systemctl --user start syncthing.service

    # Start network manager service
    tw_execute systemctl enable NetworkManager.service
    tw_execute systemctl start NetworkManager.service
}

mt_task_linux_perform_visual-tweaks () {
    tw_log "Performing visual tweaks..."

    # Install GRUB Fallout theme
    tw_execute_eval "wget -O - https://github.com/shvchk/fallout-grub-theme/raw/master/install.sh | bash"

    # Install sddm-slice theme
    tw_execute sudo pacman -S \
               qt5-graphicaleffects \
               ttf-roboto-mono \
               --noconfirm
    tw_execute sudo git clone \
               https://github.com/RadRussianRus/sddm-slice.git \
               /usr/share/sddm/themes/sddm-slice
    tw_execute_eval "echo \"[Theme]
Current=sddm-slice\" | sudo tee /etc/sddm.conf"
}
