#!/usr/bin/env bash

alias audio-restart="pulseaudio -k && pulseaudio --start"
alias wifi-connect="nmcli d wifi"

alias keymon-start="key-mon --key-timeout=1.5 --no-press-fadeout=2 --old-keys=5"

if [ $(command -v apt) ]; then
    alias mt-system-update-packages="sudo apt update && sudo apt upgrade"
elif [ $(command -v dnf) ]; then
    alias mt-system-update-packages="sudo dnf update"
elif [ $(command -v pacman) ]; then
    alias mt-system-update-packages="sudo pacman -Syu"
fi

alias mt-power-shutdown="systemctl poweroff"
alias mt-power-reboot="systemctl reboot"
alias mt-power-suspend="systemctl suspend"
alias mt-power-hibernate="systemctl hibernate"
