#!/usr/bin/env bash

# Misc
alias cl="clear"
alias gt="clear && git"
alias mt-sync-github-projects="mt-update-all-projects ${MT_WORKSPACE_PATH}"

# System commands
alias mt-system-setup="~/.setup/start"
