#!/usr/bin/env bash

# Add generic Linux scripts
export PATH=$PATH:~/.bin/linux

# Configure prompt
PS1='\u@\h:\w\$ '

# Update PATH
export PATH=$PATH:$HOME/.local/bin:$HOME/bin

# Set up aliases
alias mt-copy="xsel --clipboard --input"
alias mt-paste="xsel --clipboard --output"
alias keymon-start="key-mon --key-timeout=1.5 --no-press-fadeout=2 --old-keys=5"
