#!/usr/bin/env bash

# Update PATH for custom shell scripts
export PATH=$PATH:~/.bin

# Set custom environment variables
export MT_PATH_STORE=~/_store
export MT_PATH_WORKSPACE=~/_workspace
export MT_PATH_WORKSPACE_GITHUB=$MT_PATH_WORKSPACE/github

# Load private keys, if they exist
if [ -f "${MT_PATH_STORE}/Vault/.private-keys" ]; then
    . "${MT_PATH_STORE}/Vault/.private-keys"
fi

# Set up common aliases
alias cl="clear"
alias gt="clear && git"
alias mt-sync-github="mt-sync-projects ${MT_PATH_WORKSPACE_GITHUB}"
alias lo="lsd -l --group-dirs first"
alias po="bat"

# Load configs for the current OS
if [ $(uname) = 'Linux' ]; then
    . ~/.config/bash/config-linux
elif [ $(uname) = 'Darwin' ]; then
    . ~/.config/bash/config-mac
fi

# Start a tmux session if appropriate
if [[ ! "screen eterm-color dumb" =~ "${TERM}" ]]; then
    tmux
fi
