#!/usr/bin/env bash

# Add generic Linux scripts
export PATH=$PATH:~/.scripts/linux

# Add rest of the distro specific scripts
if [ $(command -v pacman) ]; then
    export PATH=$PATH:~/.scripts/linux/arch
elif [ $(command -v apt) ]; then
    export PATH=$PATH:~/.scripts/linux/debian
elif [ $(command -v xbps-query) ]; then
    export PATH=$PATH:~/.scripts/linux/void
fi

# Configure prompt
PS1='\u@\h:\w\$ '

# Update PATH
export PATH=$PATH:$HOME/.local/bin:$HOME/bin

# Set up aliases
alias xcopy="xsel --clipboard --input"
alias xpaste="xsel --clipboard --output"
alias keymon-start="key-mon --key-timeout=1.5 --no-press-fadeout=2 --old-keys=5"
