#!/usr/bin/env bash

# Configure prompt
PS1='\u@\h:\w\$ '

# Update PATH
export PATH=$PATH:~/.bin/linux
export PATH=$PATH:$HOME/.local/bin:$HOME/bin
export PATH=$PATH:$HOME/_store/Vault/binaries/_links

# Set up aliases
alias mt-copy="xsel --clipboard --input"
alias mt-paste="xsel --clipboard --output"

# TODO: Implement aliases with wl-clipboard for Wayland
