#!/usr/bin/env bash

# Update PATH for custom shell scripts
export PATH=$PATH:~/.scripts

# Load private keys, if they exist
if [ -f ~/.private-keys ]; then
    . ~/.private-keys
fi

# Set up common aliases
. ~/.config/bash/aliases

# Load configs for the current OS
if [ $(uname) = 'Linux' ]; then
    . ~/.config/bash/config-linux
elif [ $(uname) = 'Darwin' ]; then
    . ~/.config/bash/config-mac
fi

