#!/usr/bin/env bash

# Update PATH for custom shell scripts
export PATH=$PATH:~/.bin

# Update PATH for cargo(rust)
export PATH=$PATH:/usr/lib/cargo/bin:$HOME/.cargo/bin:$HOME/.cargo/env

# Set custom environment variables
export MT_PATH_STORE=~/_store
export MT_PATH_WORKSPACE=~/_workspace
export MT_PATH_WORKSPACE_GITHUB=$MT_PATH_WORKSPACE/github

# Load private keys, if they exist
if [ -f "${MT_PATH_STORE}/Documents/.private-keys" ]; then
    . "${MT_PATH_STORE}/Documents/.private-keys"
fi

# Set up common aliases
alias cl="clear"
alias gt="clear && git"
alias mt-sync-github="mt-sync-projects ${MT_PATH_WORKSPACE_GITHUB}"
if [ $(command -v lsd) ]; then
    alias lo="lsd -l --group-dirs first"
else
    alias lo="exa -la --group-directories-first"
fi
if [ $(command -v bat) ]; then
    alias po="bat"
else
    alias po="batcat"
fi

# Load configs for the current OS
if [ $(uname) = 'Linux' ]; then
    . ~/.config/bash/config-linux
elif [ $(uname) = 'Darwin' ]; then
    . ~/.config/bash/config-mac
fi

# Start a tmux session if appropriate
if [[ ! "screen eterm-color dumb" =~ "${TERM}" ]]; then
    tmux
fi
