(defun myTerminal/start-basic-mode ()
  (myTerminal/set-user-preferences)
  (myTerminal/set-up-repositories)
  (myTerminal/set-up-package-lists)
  (myTerminal/configure-basic-mode-packages)
  (myTerminal/set-file-associations)
  (myTerminal/configure-interface)
  (myTerminal/define-personal-functions)
  (myTerminal/define-basic-mode-keyboard-bindings)
  (myTerminal/apply-temporary-configurations))

(defun myTerminal/prompt-for-full-mode ()
  (interactive)
  (if (y-or-n-p "Not running in full-mode. Do you want to progress to full-mode?")
      (myTerminal/progress-to-full-mode)))

(defun myTerminal/progress-to-full-mode ()
  (interactive)
  (message "Progressing to full-mode...")
  (myTerminal/configure-full-mode-packages)
  (myTerminal/configure-jabber)
  (myTerminal/define-full-mode-keyboard-bindings)
  (message "Progressed to full-mode"))

;Start in basic-mode
(myTerminal/start-basic-mode)
