#!/usr/bin/env bash

# This script is an add-on to `~/.setup/start` containing device-specific setup
# for 2016 Lenovo ThinkPad X260 and mostly follows steps from
# https://wiki.archlinux.org/title/Laptop/Lenovo

# Set display scaling for the smaller screen
# The below line is useless as it places the default value '96'
# but a slightly better value could be '72'
echo "Xft.dpi: 96" > ~/.Xresources

# Improve touchpad experience with xinput
sudo xbps-install -Sy xinput # (Just in case)
sudo mkdir /etc/X11/xorg.conf.d # (Just in case)
echo "
Section \"InputClass\"
    Identifier \"libinput touchpad catchall\"
    MatchIsTouchpad \"on\"
    MatchDevicePath \"/dev/input/event*\"
    Driver \"libinput\"
EndSection
" | sudo tee /etc/X11/xorg.conf.d/40-libinput.conf
echo "
xinput set-prop 'SynPS/2 Synaptics TouchPad' 'libinput Accel Speed' 0.5
xinput set-prop 'SynPS/2 Synaptics TouchPad' 'libinput Click Method Enabled' 0 1
xinput set-prop 'SynPS/2 Synaptics TouchPad' 'libinput Tapping Enabled' 1
xinput set-prop 'SynPS/2 Synaptics TouchPad' 'libinput Natural Scrolling Enabled' 1
" > ~/.device-startup-tweaks

# Install tlp and more for power management
sudo xbps-install -Sy tlp acpi_call-dkms powertop
~/.scripts/linux/mt-battery-set-charge-thresholds
sudo ln -s /etc/sv/tlp /var/service

# TODO: Utilize fingerprint sensor
