#!/usr/bin/env bash

# This script is an add-on to `~/.setup/start` containing device-specific setup
# for 2016 Lenovo ThinkPad X1 Yoga Gen 1 and mostly follows steps from
# https://wiki.archlinux.org/title/Lenovo_ThinkPad_X1_Yoga_(Gen_1)

# Set display scaling
echo "Xft.dpi: 144" > ~/.Xresources

# Fix audio input and output
sudo xbps-install -Sy alsa-firmware sof-firmware

# Improve touchpad experience with xinput
sudo xbps-install -Sy xinput # (Just in case)
sudo mkdir /etc/X11/xorg.conf.d # (Just in case)
echo "
Section \"InputClass\"
    Identifier \"libinput touchpad catchall\"
    MatchIsTouchpad \"on\"
    MatchDevicePath \"/dev/input/event*\"
    Driver \"libinput\"
EndSection
" | sudo tee /etc/X11/xorg.conf.d/40-libinput.conf
echo "
xinput set-prop 'SynPS/2 Synaptics TouchPad' 'libinput Accel Speed' 1.0
xinput set-prop 'SynPS/2 Synaptics TouchPad' 'libinput Click Method Enabled' 0 1
xinput set-prop 'SynPS/2 Synaptics TouchPad' 'libinput Tapping Enabled' 1
xinput set-prop 'SynPS/2 Synaptics TouchPad' 'libinput Natural Scrolling Enabled' 1
" > ~/.device-startup-tweaks

# Install tlp and more for power management
sudo xbps-install -Sy tlp acpi_call-dkms powertop
~/.scripts/linux/mt-battery-set-charge-thresholds
sudo ln -s /etc/sv/tlp /var/service

# TODO: Utilize fingerprint sensor
