(defvar myTerminal/my-keyboard-bindings 
  (list '("C-~" . myTerminal/set-zoning)
        '("C-!" . zone-leave-me-alone)
        '("C-M-)" . transparency-increase)
        '("C-M-(" . transparency-decrease)
        '("C-c C-l" . nlinum-mode)
        '("C-}" . mc/mark-next-like-this)
        '("C-{" . mc/mark-previous-like-this)
        '("C-|" . mc/mark-all-like-this)
        '("C->" . ace-jump-mode)
        '("C-<" . ace-jump-mode-pop-mark)
        '("M-/" . undo-tree-visualize)
        '("M-y" . browse-kill-ring)
        '("C-M-]" . e2wm:start-management)
        '("C-M-[" . e2wm:stop-management)
        '("C-\"" . theme-looper:enable-next-theme)
        '("C-M-'" . myTerminal-controls:open-controls)
        '("M-<down>" . myTerminal/move-line-down)
        '("M-<up>" . myTerminal/move-line-up)
        '("C-=" . myTerminal/eval-and-replace)
        '("M-x" . smex)
        '("C-c C-c M-x" . execute-extended-command)
        '("C-M-z" . switch-window)))

(mapc 'myTerminal/apply-keyboard-bindings
      myTerminal/my-keyboard-bindings)
