#!/usr/bin/env bash

# This script is an add-on to `~/.setup/start` containing device-specific setup
# for 2020 Lenovo ThinkPad X1 Extreme and mostly follows steps from
# https://wiki.archlinux.org/index.php/Lenovo_ThinkPad_X1_Extreme

# Set display scaling for HiDPI
echo "Xft.dpi: 192" > ~/.Xresources
echo "[X11]
EnableHiDPI=true
[Wayland]
EnableHiDPI=true" | sudo tee /etc/sddm.conf

# Enable bluetooth service
# (This might just be a temporary Arch issue)
systemctl enable bluetooth
systemctl start bluetooth

# Install Nvidia drivers
. ~/.setup/linux/other/nvidia-latest

# Fix audio input and output
sudo pacman -S alsa-firmware sof-firmware --noconfirm

# Enable Dolby Atmos Effect through pulseeffects
sudo paru -S pulseeffects-legacy --noconfirm
pulseeffects
bash -c "$(curl -fsSL https://raw.githubusercontent.com/JackHack96/PulseEffects-Presets/pulseeffects/install.sh)"

# Enable microphone noise reduction
echo "
### Enable Echo/Noise-Cancellation
load-module module-echo-cancel use_master_format=1 aec_method=webrtc aec_args=\"beamforming=1 mic_geometry=-0.0257,0,0,0.0257,0,0\" source_name=echoCancel_source sink_name=echoCancel_sink
set-default-source echoCancel_source
set-default-sink echoCancel_sink" | sudo tee -a /etc/pulse/default.pa

# Improve touchpad experience
echo "
xinput set-prop 'SynPS/2 Synaptics TouchPad' 'libinput Accel Speed' 0.5
xinput set-prop 'SynPS/2 Synaptics TouchPad' 'libinput Click Method Enabled' 0 1
xinput set-prop 'SynPS/2 Synaptics TouchPad' 'libinput Tapping Enabled' 1
xinput set-prop 'SynPS/2 Synaptics TouchPad' 'libinput Natural Scrolling Enabled' 1
" > ~/.device-startup-tweaks

# Install tlp and more for power management
sudo pacman -S tlp acpi_call powertop --noconfirm
~/.bin/linux/mt-battery-set-charge-thresholds
systemctl enable tlp
systemctl start tlp

# TODO: Fix display scaling

# TODO: Fix display flickering on integrated mode

# TODO: Utilize fingerprint sensor
