#!/usr/bin/env bash

command=$1

case "${1}" in
    e | express )
        exec chromium & disown
        exec emacs & disown
        exec logseq & disown
        exec keepassxc & disown
        ;;

    g | gaming )
        exec steam & disown
        ;;

    *)
        exec chromium & disown
        exec signal-desktop & disown
        exec Telegram & disown
        exec emacs & disown
        exec libre-wolf & disown
        exec logseq & disown
        exec better-bird & disown
        exec keepassxc & disown
        ;;
esac
