#!/usr/bin/env bash

command=$1

case "${1}" in
    e | express )
        exec emacs & disown
        exec brave & disown
        exec brave-browser & disown
        exec keepassxc & disown
        ;;

    g | gaming )
        exec steam & disown
        ;;

    *)
        exec emacs & disown
        exec schildi & disown
        exec brave & disown
        exec brave-browser & disown
        exec thunar & disown
        exec thunderbird & disown
        exec keepassxc & disown
        ;;
esac
