#!/usr/bin/env bash

# Install latest Nvidia drivers
. ~/.scripts/mt-arch-nvidia-latest-setup

# Install prime
sudo pacman -S nvidia-prime --noconfirm

# Install optimus-manager
yay -S optimus-manager optimus-manager-qt --noconfirm
