#!/usr/bin/env bash

# This script is an add-on to `~/.setup/start` containing device-specific setup
# for 2020 Lenovo ThinkPad X1 Extreme (Excelsior)

# Setup Nvidia optimus for GPU
. ~/.scripts/mt-arch-nvidia-optimus-setup

# TODO: Implement the rest
