#!/usr/bin/env bash

# This script is an add-on to `~/.setup/start` containing device-specific setup
# for 2020 Lenovo ThinkPad X1 Extreme (Excelsior)

# Set .XResources for HiDPI
echo "Xft.dpi: 180" > ~/.Xresources

# Enable bluetooth service
# (This might just be a temporary Arch issue)
systemctl enable bluetooth
systemctl start bluetooth

# Setup Nvidia optimus for GPU
. ~/.scripts/mt-arch-nvidia-optimus-setup

# Fix 'Dummy Output' for audio
echo "options snd_hda_intel dmic_detect=0" | sudo tee /etc/modprobe.d/disable_dmic.conf

# TODO: Implement the rest
