#!/usr/bin/env node

/* global require process console */

const { argv: [program, thisFile, inputDir, outputFile] } = process;
const { log } = console;

const { inflateInput, getFileStats, getVerticalList, writeToFile } = require('../.assets/libs/node');

const files = inflateInput([inputDir]);

const fileMap = {};
for (let i = 0; i < files.length; i++) {
    const [filePath, fileName, fileSize] = getFileStats(files[i]);

    const entry = fileMap[fileName];

    if (entry && entry[0] === fileSize) {
        entry.push(filePath);
    } else {
        fileMap[fileName] = [fileSize, filePath];
    }
}

const duplicates = Object.keys(fileMap)
    .filter(k => fileMap[k].length > 2)
    .map(k => `${k}: ${fileMap[k].join(', ')}`);

const listOfDuplicates = getVerticalList(duplicates);

log(listOfDuplicates);

if (outputFile) {
    writeToFile(outputFile, listOfDuplicates);
}
