#!/usr/bin/env node

/* global require process console */

const { argv: [program, thisFile, inputDir, outputFile] } = process;
const { log } = console;

const { inflateInput, getVerticalList, writeToFile } = require('../.assets/libs/node');

const listOfFiles = getVerticalList(inflateInput([inputDir]));

log(listOfFiles);

if (outputFile) {
    writeToFile(outputFile, listOfFiles);
}
