#!/usr/bin/env node

/* global require process console */

const { argv: [program, thisFile, inputDir] } = process;
const { log } = console;

const { inflateInput, getVerticalList } = require('../.assets/libs/node');

const listOfFiles = getVerticalList(inflateInput([inputDir]));

log(listOfFiles);
