#!/usr/bin/env bash

command=$1

run_for_linux () {
    case "${command}" in
        "shutdown" | "poweroff" )
            systemctl poweroff
            ;;

        "restart" | "reboot" )
            systemctl reboot
            ;;

        "sleep" | "suspend" )
            systemctl suspend
            ;;

        "hibernate" | "poweroff" )
            systemctl hibernate
            ;;

        "awake" )
            systemctl mask sleep.target suspend.target
            ;;

        "sleepy" )
            systemctl unmask sleep.target suspend.target
            ;;

        *)
            echo "Not implemented!"
            ;;
    esac
}

run_for_mac () {
    case "${command}" in
        "shutdown" | "poweroff" )
            sudo shutdown
            ;;

        "restart" | "reboot" )
            sudo reboot
            ;;

        *)
            echo "Not implemented!"
            ;;
    esac
}

main () {
    if [ $(uname) = 'Linux' ]; then
        run_for_linux
    elif [ $(uname) = 'Darwin' ]; then
        run_for_mac
    fi
}

main
