#!/usr/bin/env bash

update_linux () {
    if [ $(command -v apt) ]; then
        sudo apt update -y && sudo apt upgrade -y
    elif [ $(command -v dnf) ]; then
        sudo dnf update -y
    elif [ $(command -v pacman) ]; then
        sudo pacman -Syu --noconfirm
    fi
}

update_mac () {
    brew update && brew upgrade
}

main () {
    if [ $(uname) = 'Linux' ]; then
        update_linux
    elif [ $(uname) = 'Darwin' ]; then
        update_mac
    fi
}

main
