#!/usr/bin/env bash

tw_log "Installing core packages..."
tw_execute sudo apt install \
           tmux \
           fish \
           fd-find \
           exa \
           bat \
           ncdu \
           ripgrep \
           fzf \
           emacs \
           aspell \
           aspell-en \
           tig \
           ranger \
           xarchiver \
           htop \
           udisks2 \
           network-manager \
           dnsutils \
           weechat \
           docker \
           npm \
           brightnessctl \
           acpi \
           neofetch \
           wget \
           ssh

tw_log "Installing graphical packages..."
tw_execute sudo apt install \
           compton \
           i3 \
           xfce4 \
           feh \
           rofi \
           kitty \
           udiskie \
           gparted \
           thunar \
           gvfs \
           firefox-esr \
           chromium \
           keepassxc \
           evolution \
           transmission \
           virt-manager \
           libreoffice \
           blueman \
           shotwell \
           gimp \
           darktable \
           clementine \
           mpg123 \
           pavucontrol \
           pulseaudio \
           pulseeffects \
           audacity \
           easytag \
           vlc \
           handbrake \
           blender \
           youtube-dl \
           kodi \
           flameshot \
           obs-studio \
           peek \
           steam \
           barrier \
           libgl1-nvidia-glvnd-glx:i386

tw_log "Installing more packages..."
tw_execute sudo apt install \
           syncthing-gtk \
           numlockx

# TODO: Fix for Debian: find a way to install the below graphical packages
tw_log "The following packages were not found on Debian archives:"
tw_log "tunnelbear, rememberthemilk, dynalist, pcloud, key-mon, gamehub, balena-etcher, nomachine, edex-ui"

# TODO: Fix for Debian: picom is here compton
# TODO: Fix for Debian: dmenu is here i3-dmenu-desktop
# TODO: Fix for Debian: need to replace firefox-esr with firefox-developer-edition

tw_log "Installing packages through snap..."
tw_execute sudo snap install discord
tw_execute sudo snap install postman
tw_execute sudo snap install rustup --classic
tw_execute sudo snap install authy --beta

tw_log "Installing packages through flatpak..."
# None for now

tw_log "Performing a few package-dependent configs..."
tw_execute sudo usermod -aG libvirt ismail
tw_execute xdg-settings set default-web-browser firefox-esr.desktop
