#!/usr/bin/env bash

mt_log "Setting up peripherals..."

mt_log "Installing packages for Razer devices..."
# Below steps have been obtained from https://polychromatic.app/download/ubuntu
sudo add-apt-repository ppa:openrazer/stable
sudo add-apt-repository ppa:polychromatic/stable
sudo apt update
sudo apt install -y \
     openrazer-meta \
     polychromatic

mt_log "A reboot may be required for the Razer dameon to be able to detect attached devices."
