#!/usr/bin/env bash

# Function to install peripheral drivers
mt_task_linux_install_peripherals_drivers () {
    tw_log "Installing packages for Razer devices..."

    # Add sources for Razer
    tw_execute echo 'deb http://download.opensuse.org/repositories/hardware:/razer/Debian_Testing/ /' | sudo tee /etc/apt/sources.list.d/hardware:razer.list
    tw_execute curl -fsSL https://download.opensuse.org/repositories/hardware:razer/Debian_Testing/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/hardware_razer.gpg > /dev/null
    tw_execute sudo apt update

    # Install openrazer and razer-genie
    tw_execute sudo apt install -y \
               openrazer-meta razergenie

    # Add current user to group 'plugdev'
    tw_execute sudo gpasswd -a $USER plugdev
}

# Function to setup startup services
mt_task_linux_setup_startup_services () {
    # Setup syncthing service
    tw_execute systemctl --user enable syncthing.service
    tw_execute systemctl --user start syncthing.service

    # Start bluetooth service
    tw_execute systemctl enable bluetooth
    tw_execute systemctl start bluetooth

    # Start ssh service
    tw_execute systemctl enable ssh
    tw_execute systemctl start ssh
}

# Function to perform visual tweaks at GRUB and DM level
mt_task_linux_perform_visual_tweaks () {
    tw_log "Performing visual tweaks..."

    # Install GRUB Fallout theme
    tw_execute sudo apt install -y \
               unzip
    tw_execute_eval "wget -O - https://github.com/shvchk/fallout-grub-theme/raw/master/install.sh | bash"

    # Install sddm-slice theme
    tw_execute sudo apt install -y \
               qml-module-qtgraphicaleffects \
               qml-module-qtquick-layouts \
               fonts-roboto
    tw_execute sudo git clone \
               https://github.com/RadRussianRus/sddm-slice.git \
               /usr/share/sddm/themes/sddm-slice
    tw_execute_eval "echo \"[Theme]
Current=sddm-slice\" | sudo tee /etc/sddm.conf"
}
