#!/usr/bin/env bash

# Install brew
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# Install cask
brew tap caskroom/cask

# Install packages from brew
brew install \
     tig \
     node \
     fish \
     aspell \
     syncthing \
     youtube-dl

# Install essential packages from brew cask
brew cask install \
     hyper \
     emacs \
     google-chrome \
     shiftit \
     postman \
     mounty

# Install network packages from brew cask
brew cask install \
     dropbox \
     google-backup-and-sync \
     megasync \
     filezilla \
     transmission \
     tunnelbear \
     remember-the-milk \
     dynalist \
     riot \
     telegram \
     discord \
     slack \
     thunderbird \
     spotify

# Install multimedia packages from brew cask
brew cask install \
     vlc \
     clementine \
     kodi \
     xnviewmp \
     gimp \
     handbrake \
     kid3

# Install gaming packages from brew cask
brew cask install \
     steam \
     origin \
     sony-remoteplay

# Install screencast packages from brew cask
brew cask install \
     licecap \
     keycastr

# Install misc packages from brew cask
brew cask install \
     libreoffice \
     virtualbox \
     crossover \
     docker \
     diffmerge \
     android-file-transfer

# Install fonts
brew cask install \
     font-inconsolata \
     font-liberation-sans \
     font-roboto-mono \
     caskroom/fonts/font-fira-code

# Manual packages
# - Install pCloud Drive from https://www.pcloud.com
# - Install Audacity from https://www.fosshub.com/Audacity.html/audacity-macos-2.2.0.dmg
# - Install LAME from https://lame.buanzo.org/#lameosxdl

# Missing packages
# - Droid Sans

# Inbuilt packages
# - Git
