#!/usr/bin/env bash

# Enable showing of hidden files in finder
defaults write com.apple.Finder AppleShowAllFiles YES
killall Finder

# Install software packages
. ~/.system/setup/fedora/install-packages
