#!/usr/bin/env bash

# Enable showing of hidden files in finder
defaults write com.apple.Finder AppleShowAllFiles YES
killall Finder

# Install software packages
. ~/.system/setup/fedora/install-packages

# Add fish-shell as a valid shell
echo "/usr/local/bin/fish" | sudo tee -a /etc/shells

# Change shell to fish-shell
chsh -s /usr/local/bin/fish
