#!/usr/bin/env bash

# Function to set up Docker
mt_task_linux_setup_docker () {
    tw_log "Setting up Docker..."
    tw_execute sudo groupadd docker
    tw_execute sudo gpasswd -a ${USER} docker

    case "${tw_init_system}" in
        SystemD)
            tw_execute sudo systemctl enable docker
            ;;

        Runit)
            tw_execute sudo ln -s /etc/sv/docker /var/service
            ;;
    esac
}

# Function to change user shell
mt_task_linux_change_user_shell () {
    tw_log "Changing shell to fish..."
    if ! [ "$(cat /etc/shells | grep "/fish")" ]; then
        tw_execute_eval "echo \"$(which fish)\" | sudo tee -a /etc/shells"
    fi
    tw_task_change_user_shell
}

# Function to install toolchain for Rust
mt_task_linux_install_rust_toolchain() {
    tw_log "Installing stable toolchain for Rust..."
    if [ $(command -v rustup-init) ]; then
        tw_execute rustup-init --default-toolchain stable --profile default -y
    else
        tw_execute rustup toolchain install stable
    fi
}

# Function to set up GUI
mt_task_linux_setup_gui () {
    tw_log "Setting up GUI..."
    tw_task_setup_gui false
}

# Function to apply graphical theming
mt_task_linux_apply_graphical_theming () {
    rm -rf ~/_temp

    tw_log "Installing GTK theme..."
    tw_execute mkdir -p ~/.local/share/themes
    tw_execute git clone https://github.com/WernerFP/Shades-of-gray-theme.git ~/_temp
    tw_execute mv ~/_temp/Shades-of* ~/.local/share/themes/
    tw_execute rm -rf ~/_temp

    tw_log "Installing icon theme..."
    tw_execute mkdir -p ~/.local/share/icons
    tw_execute git clone https://github.com/madmaxms/iconpack-obsidian ~/_temp
    tw_execute mv ~/_temp/Obsidian* ~/.local/share/icons/
    tw_execute rm -rf ~/_temp

    tw_log "Installing cursor theme..."
    tw_execute mkdir -p ~/.local/share/icons
    tw_execute mkdir ~/_temp
    tw_execute cd ~/_temp
    tw_execute wget https://github.com/ful1e5/Bibata_Cursor/releases/download/v1.1.1/Bibata.tar.gz
    tw_execute tar -xvf Bibata.tar.gz
    tw_execute mv ~/_temp/Bibata-*  ~/.local/share/icons
    tw_execute cd ~/
    tw_execute rm -rf ~/_temp
}

# Function to install fonts
mt_task_linux_install_fonts () {
    tw_execute rm -rf ~/_temp

    tw_log "Installing FontAwesome..."
    tw_execute mkdir -p ~/.local/share/fonts
    tw_execute git clone https://github.com/FortAwesome/Font-Awesome ~/_temp
    tw_execute mv ~/_temp/otfs ~/.local/share/fonts/FontAwesome
    tw_execute rm -rf ~/_temp

    tw_log "Installing OpenSans..."
    tw_execute mkdir -p ~/.local/share/fonts
    tw_execute git clone https://github.com/googlefonts/opensans ~/_temp
    tw_execute mv ~/_temp/fonts/ttf ~/.local/share/fonts/OpenSans
    tw_execute rm -rf ~/_temp

    tw_log "Installing Inconsolata..."
    tw_execute mkdir -p ~/.local/share/fonts
    tw_execute git clone https://github.com/googlefonts/inconsolata ~/_temp
    tw_execute mv ~/_temp/fonts/ttf ~/.local/share/fonts/Inconsolata
    tw_execute rm -rf ~/_temp

    tw_log "Installing Roboto Mono..."
    tw_execute mkdir -p ~/.local/share/fonts
    tw_execute git clone https://github.com/googlefonts/RobotoMono ~/_temp
    tw_execute mv ~/_temp/fonts/ttf ~/.local/share/fonts/RobotoMono
    tw_execute rm -rf ~/_temp

    tw_log "Installing Droid..."
    tw_execute mkdir -p ~/.local/share/fonts
    tw_execute git clone https://github.com/grays/droid-fonts ~/_temp
    tw_execute mv ~/_temp/droid ~/.local/share/fonts/Droid
    tw_execute rm -rf ~/_temp

    tw_log "Installing FiraCode..."
    tw_execute mkdir -p ~/.local/share/fonts
    tw_execute git clone https://github.com/tonsky/FiraCode ~/_temp
    tw_execute mv ~/_temp/distr/ttf ~/.local/share/fonts/FiraCode
    tw_execute rm -rf ~/_temp

    tw_log "Installing Liberation..."
    tw_execute mkdir -p ~/.local/share/fonts
    tw_execute mkdir ~/_temp
    tw_execute cd ~/_temp
    tw_execute wget https://github.com/liberationfonts/liberation-fonts/files/6418984/liberation-fonts-ttf-2.1.4.tar.gz
    tw_execute tar -xvf liberation-fonts-ttf-2.1.4.tar.gz
    tw_execute mkdir ~/.local/share/fonts/Liberation
    tw_execute mv ~/_temp/liberation-fonts-ttf-2.1.4/Liberation*  ~/.local/share/fonts/Liberation/
    tw_execute cd ~/
    tw_execute rm -rf ~/_temp
}

# Function to configure event tweaks
mt_task_linux_configure_event_tweaks () {
    tw_log "Enabling touch scrolling for Firefox..."
    tw_execute echo "
MOZ_USE_XINPUT2 DEFAULT=1
" | sudo tee -a /etc/security/pam_env.conf
}
